### ISSUE TITLE
Bug: default behavior of BaseModelView.is_action_allowed is not as expected

### ISSUE THREAD

**Issue by dolamroth** [jowilf/starlette-admin#101]
**Describe the bug**
By default `BaseModelView.is_action_allowed` returns True for `delete_action`, even if `can_delete` returns False.

**Environment (please complete the following information):**
- starlette==0.25.0
- starlette-admin==0.5.2
- SQLAlchemy==1.4.46

**Additional context**
To fix the bug, coroutine `self.can_delete(request)` should be awaited.

```
async def is_action_allowed(self, request: Request, name: str) -> bool:
    if name == "delete":
        return await self.can_delete(request)
    return True
```

**Comment by jowilf** [comment]
https://github.com/jowilf/starlette-admin/blob/cf42f6d8977ef02f064165f507992af9d9d2dc15/starlette_admin/views.py#L455
It is a synchronous method and can not be awaited

Refer to https://github.com/jowilf/starlette-admin-demo/blob/main/app/sqla/views.py for usage example

**Comment by dolamroth** [comment]
I see, my bad. I wanted to suggest to use async, since one can potentially access AsyncSession from request in those methods, but then I saw that those methods are used as templatetags, and starlette disencourages to use async logic in template rendering https://www.starlette.io/templates/#asynchronous-template-rendering

Thank you for your time 👍
