### ISSUE TITLE
Enhancement: input data in custom action

### ISSUE THREAD

**Issue by Ilya-Green** [jowilf/starlette-admin#119]
Thank you very much for the great framework!

I want to ask is there any way to send some input data for the custom action. For example, when you need to do some bulk edits: replace some specified field for all selected rows with some text/int/etc. And other operations that might require data for the execution.
Without this feature, you have to edit all the entries manually, which can spend a very long time.

**Comment by jowilf** [comment]
This feature is under review #61. Any suggestions and PR are welcome!
