### ISSUE TITLE
Bug: EnumField options displayed incorrectly in list/detail templates [2]

### ISSUE THREAD

**Issue by sshghoult** [jowilf/starlette-admin#123]
The issue is the same as reported in #95. I'm terribly sorry about leaving it hanging for 3 weeks, but that problem was in my backlog all this time. Opening a new issue so you don't miss a comment on the old one.
However, this once I bring you reproducable example. 

I cloned and started up [starlette-admin-demo](https://github.com/jowilf/starlette-admin-demo), set up the sqla admin as per readme.md and applied the following changes:

_app/sqla/models.py:_ 
updated  Gender enum content
```
class Gender(str, enum.Enum):
    MALE = "Mâle"
    FEMALE = "Femme"
    UNKNOWN = 'ignoré'
    STORED = 'LaBeL'
```

_app/sqla/views.py:_ 
added _sex_ field to the model View via clean EnumField, not inferred from a model; added a choice list, copied from the Gender enum. added EnumFields based on both enum and choices_list (one of these is always commented out, of course)
```
sex_choices = [('MALE', 'Mâle'), ('FEMALE', 'Femme'), ('UNKNOWN', 'ignoré'), ('STORED', 'LaBeL')]

class UserView(ModelView):
    page_size_options = [5, 10, 25, -1]
    fields = [
        "id",
        "full_name",
        EmailField("username"),
        "avatar",
        "posts",
        EnumField('sex', choices=sex_choices),
        # EnumField('sex', enum=Gender),
        CommentCounterField("comments_counter", label="Number of Comments"),
        "comments",
    ]
    ...
```

If **Enum-based** EnumField is used, then all the views (list, detail, create, edit) always display **names of the enumeration members**, and never their values.
![image](https://user-images.githubusercontent.com/50514492/225632841-cef116db-739f-4723-bb80-0f32d4559a70.png)
![image](https://user-images.githubusercontent.com/50514492/225632948-26dcd9d0-8192-49e8-95ff-32970df46c15.png)

if **choices-list-based** EnumField is used, then **create/edit views** display values (per Django terminology) and **list/detail views** display labels.
![image](https://user-images.githubusercontent.com/50514492/225634099-7fa9a57f-a890-4f57-9321-f395c0c66efb.png)
![image](https://user-images.githubusercontent.com/50514492/225634278-80195458-74b3-42f3-9a81-1d71bbf533b7.png)
![image](https://user-images.githubusercontent.com/50514492/225634425-046bb5fb-40d4-43d8-9939-653ff01ecd33.png)

It's hard to notice when values and names of members a similar to each other and frontend styles format the received value. However, it's rather clear when values are written in another language.

I believe, the template shenenigans I mentioned in #95 are still the key to the core of the problem. The choices-list-based field is displayed correctly in create/edit forms, because options' values and labels are explicitly set in parts of generated html in _starlette_admin/templates/forms/enum.html_. 
EnumField.serialize_value doesn't seem to be actually used during rendering (though I might be wrong, as I don't know this codebase this thorougly).

Sidenote: when choices-list-based EnumField is used, current value is erased on edit. It's not a case when the Enum-based field is used.
![image](https://user-images.githubusercontent.com/50514492/225635415-c41d582d-066e-4c97-beeb-f374253ae8f5.png)
![image](https://user-images.githubusercontent.com/50514492/225636265-6ce5cece-7903-4303-bcaf-b7c47bb6b520.png)

**Comment by jowilf** [comment]
The `Enum` name is used as label inside `EnumField`. It's the same behavior with wtform-sqlalchemy

It better to use choices-list based `EnumField` when you want to customize the label

For example:

```py
EnumField(
    "status",
    choices=[("d", _("Draft")), ("p", _("Published")), ("w", _("Withdrawn"))],
),
```

**Comment by jowilf** [comment]
> Sidenote: when choices-list-based EnumField is used, current value is erased on edit. It's not a case when the Enum-based field is used.

I'm not able to reproduce, can you provide a minimum example ? just a simple model with 2-3 columns

**Comment by sshghoult** [comment]
As per description, I can reproduce the issue with the model "User" at app/sqla/models.py at your [starlette-admin-demo](https://github.com/jowilf/starlette-admin-demo) and aforementioned updates to the view

**Comment by jowilf** [comment]
Your error is related to your choices list -> sex_choices = [('MALE', 'Mâle'), ('FEMALE', 'Femme'), ('UNKNOWN', 'ignoré'), ('STORED', 'LaBeL')]

As you can see in the documentation ([EnumField](https://jowilf.github.io/starlette-admin/api/fields/#starlette_admin.fields.EnumField)), the choices parameters is a list of (value, label) pairs. 

The valid list is -> 
```py 
sex_choices = [('Mâle', 'MALE'), ('Femme', 'FEMALE'), ('ignoré', 'UNKNOWN'), ('LaBeL', 'STORED')]
```

Another example is this : 

if your an enum class like this:

```py
class Counter(str, enum.Enum):
    ONE = 1
    TWO = 2
```
The equivalent EnumField is:

```py
EnumField("choice", choices=((1, "One"), (2, "Two")), coerce=int),
```

**Comment by sshghoult** [comment]
I'm sorry, but your first example contradicts the example in the documentation for the ([EnumField](https://jowilf.github.io/starlette-admin/api/fields/#starlette_admin.fields.EnumField))

```
class MyModel:
    language: str

class MyModelView(ModelView):
    fields = [
        EnumField(
            "language",
            choices=[("cpp", "C++"), ("py", "Python"), ("text", "Plain Text")],
        )
    ]
```
Clearly, the choices list here comprises (value, label) tuples.

I believe one of us must be misinterpreting the difference between the value and label terms. I use them in the way defined in the [Django](https://docs.djangoproject.com/en/4.1/ref/models/fields/#enumeration-types), where value is a "thing" stored in the database, and label is a human-readable serialization of the "thing" to display to the user. This notion seems to comply with the example in the documentation, however, contradicts the first example you've just provided (though complies with the second).

I must've caused that confusion by initially mixing up the value and label entities in  
> if choices-list-based EnumField is used, then create/edit views display values (per Django terminology) and list/detail views display labels.
The correct version of the problem description that is actually in accordance with Django terminology is 
**" if choices-list-based EnumField is used, then create/edit views display labels (per Django terminology) and list/detail views display values."**
Sorry about that.

Moreover, with whichever ordering of value and label being correct, there is still inconsistency in the display of the field in the different views, which is a problem.

**Comment by jowilf** [comment]
The isssue is with sqlalchemy itself which store the **enum names** in database(https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum). The example in the documentation work well with  MongoEngine, Odmantic 

More info -> https://stackoverflow.com/questions/47206201/how-to-use-enum-with-sqlalchemy-and-alembic

**Comment by sshghoult** [comment]
It doesn't seem to be specific to SQLAlchemy, as I experience the same display inconsitency on custom backend. Allow me to highlight that create/edit views display everything correctly for both SQLA and custom backend.

Besides, on retrieval, SQLModel with a propper Enum as an attribute value is instantiated, so the pecularities of the sqla enum storage mechanism can't leak to the admin level.

**Comment by sshghoult** [comment]
Update: figured out the case on my custom backend, but it's applicable for SQLA as well, as per SO post you mentioned. 

When model and raw_obj are passed to render, and raw_obj has a defined on the persistence level Enum as a value for a field, during the execution of EnumField._get_label that is called during serialization, the persistence-level Enum hijacks the control flow and forces it's name to be used in the display. Choices list defined on the EnumField as a part of a ModelView is therefore ignored.
The inconsistency of the views and out-of-the-box correctness of the edit/create view is caused by the direct usage of the `field.choices` in the _forms/enum.html_.

As I understand, by mentioning the details of enum storage at sqla you implied that such forwarding and hijacking are obvious -- they really aren't, and I'd love to see it at the very least denoted in the docs, and much sooner fixed.

**Comment by jowilf** [comment]
> When model and raw_obj are passed to render, and raw_obj has a defined on the persistence level Enum as a value for a field, during the execution of EnumField._get_label that is called during serialization, the persistence-level Enum hijacks the control flow and forces it's name to be used in the display. Choices list defined on the EnumField as a part of a ModelView is therefore ignored.

Are you trying to override a template? `raw_obj` is your database model instance which is not touch by `starlette-admin`. It can be useful in some case to access deep level values (e.g. https://github.com/jowilf/starlette-admin-demo/blob/main/templates/admin/sqla/post_detail.html). Otherwise, you should use `model` which contains the serialized values.

**Comment by sshghoult** [comment]
> https://github.com/jowilf/starlette-admin/issues/123#issuecomment-1476485332
There doesn't seem to be anything wrong with it.


> https://github.com/jowilf/starlette-admin/issues/123#issuecomment-1476494167
Yes, raw_obj that is passed directly to the call of the TemplateResponse is not used in the templates, however, it serves as a parameter for a ModelView.serialize that defines the content of the view. The value stored in the raw_obj (which is an instance of Enum) is passed to the Field.serialize_value through the calls of ModelView.serialize and ModelView.serialize_field_value, where the type-check condition catches it and uses the name of the instance in the display. That is the default callstack for the rendering process, and that check in the Field.serialize_value is why the low-level enum leaks to the display.

```
class EnumFiels:
    ...

    def _get_label(self, value: Any) -> Any:
        if isinstance(value, Enum):
            return value.name
        for v, label in self.choices:
            if value == v:
                return label
        raise ValueError(f"Invalid choice value: {value}")
```

**Comment by jowilf** [comment]
As I said previously, `raw_obj` is your model instance returned by `find_by_pk` method, It's not serialized ([ref](https://github.com/jowilf/starlette-admin/blob/3cadf4a5a996a10c6d959324b8d6f7479c4a2f46/starlette_admin/base.py#L421)). Only `obj` is serialized and should be used to access data. 

Also, `raw_obj` is only available for model detail view. If you are trying to overriding a template for a field you should use `data` to access the field value -> https://jowilf.github.io/starlette-admin/advanced/custom-field/#form

But I think we are getting to far from your initial issue. 

> There doesn't seem to be anything wrong with it.

It still not clear for me the issue your are facing. can you provide a minimum example to reproduce it, and a clear description?  Otherwise, sorry but I can't help you. Thank

**Comment by sshghoult** [comment]
It seems that we are completely unable to understand each other's side of the question. Thank you for the time spent trying to help me.
