### ISSUE TITLE
Enhancement: Optional WYSIWYG editor for TextAreaField

### ISSUE THREAD

**Issue by sinisaos** [jowilf/starlette-admin#130]
First of all I want to thank you for a great project. What I liked most is both async and sync support and that everything works out of the box without single problem (including one-to-many and many-to-many relational fields, which is not the case in most other admin interfaces)

**Describe the solution you'd like**
Tabler default WYSIWYG editor is [TinyMCE](https://preview.tabler.io/docs/tinymce.html). The solution would be something like this
```python
# in fields.py
@dataclass
class RichTextField(TextAreaField):
    """This field is an optional field used to represent a WYSIWYG editor
    for long text content.
    """

    form_template: str = "forms/richtext.html"
```
after that, we create `richtext.html` in `forms` directory and include support for TinyMCE in it.

**Usage**
We can use this new field like all other fields in `ModelView` `fields` property like this
```python
class PostView(SQLModelView):
    fields = [
        "id",
        "title",
        RichTextField("content"),
    ]
```
If `RichTextField` is not provided we get default `textarea` in forms.

If you agree with this changes I can try to make PR. Thanks again.

**Comment by jowilf** [comment]
Thank for your suggestion. A PR is welcome! But I prefer `TinyMCEEditorField`

**Comment by sinisaos** [comment]
> Thank for your suggestion. A PR is welcome! But I prefer `TinyMCEEditorField`

I will use that field name. I have just one more question. Do you want me to use TinyMCE from the CDN in template or to include the TinyMCE files in a `statics` folder (50+ files)?

**Comment by jowilf** [comment]
I'm not sure we need all of them. Tabler use  only the `tinymce.min.js` file I think.

**Comment by sinisaos** [comment]
That's what I thought too, but unfortunately, that one file is not enough (we need to include at least 5-6 js files and several css files) and that's why I thought since that field is optional, we could use TinyMCE from CDN.

**Comment by jowilf** [comment]
In that case it's better to use from CDN.
