### ISSUE TITLE
Bug: Link is brocken to inter.css

### ISSUE THREAD

**Issue by MatsiukMykola** [jowilf/starlette-admin#140]
**Describe the bug**

**To Reproduce**
Explain how to reproduce the bug.

**Environment (please complete the following information):**
 - Starlette-Admin version: [e.g. 0.3.2]
 - ORM/ODMs: [SQLAlchemy, MongoEngine, ...]

**Additional context**

link is broken: https://rsms.me/inter/inter.css
change please to:
https://unpkg.com/inter-ui@3.19.3/inter.css

**Comment by abhishek-compro** [comment]
Both links are working for me

**Comment by MatsiukMykola** [comment]
in Ukraine not work, 
I discuss my friend in the EU zone - the same issue

https://unpkg.com/inter-ui@3.19.3/inter.css - works fine everywhere

**Comment by abhishek-compro** [comment]
Okay. But I think https://unpkg.com/inter-ui@latest/inter.css is a better alternative.

**Comment by jowilf** [comment]
Thank you for your support, @abhishek-compro.

Sorry @MatsiukMykola, the official CDN link for Inter is https://rsms.me/inter/inter.css ([ref](https://github.com/rsms/inter#using--installing-inter)) and it's working.

In case your network issue persists, a workaround is to override the `base.html` file in your templates folder and manually modify the link.
