### ISSUE TITLE
Bug: Static files like tabler.min.css are not rendered in HTML as HTTPS links

### ISSUE THREAD

**Issue by abhishek-compro** [jowilf/starlette-admin#143]
After deployment the /admin homepage is HTTPS but all other links in the HTML source are HTTP links which prevents loading them.

# Reproduction steps
1. Deploy it to a production server with an HTTPS link
2. Go to https://domain.com/admin
3. No JS / CSS is loaded and login is also compromised due to HTTP link

# Environment
 - Starlette-Admin 0.6.0
 - SQLAlchemy 2.0.5.post1

**Comment by jowilf** [comment]
If you are running your app behing a proxy server like Trafefik or Nginx , you need to run uvicorn with `--forwarded-allow-ips='*'` and `--proxy-headers`. 

More info -> https://www.uvicorn.org/deployment/#running-behind-nginx

**Comment by abhishek-compro** [comment]
Thanks that fixes the issue. But I have 2 things to say.

1. Most of fastapi UI like **/docs** and **/redoc** are rendered nicely and login works too
2. This isn't obvious. Maybe you can provide a link to the documentation so that people can know what may cause the issue.
