### ISSUE TITLE
Enhancement: not display sensitive data in relation form

### ISSUE THREAD

**Issue by Ilya-Green** [jowilf/starlette-admin#146]
Is there any opportunity to not display fields according to persmision level for the users?
![image](https://user-images.githubusercontent.com/105509043/228617957-b1105320-e094-4920-9ec8-d677e32f4d01.png)

For now there is some invonvenience in safety by displaying some sensitive information whoever the user is
Even if i try to restrict field as much as possible it displays information in relation field of other view:
```
@dataclass
class PasswordField(StringField):
    """A StringField, except renders an `<input type="password">`."""

    input_type: str = "password"
    class_: str = "field-password form-control"
    exclude_from_list: Optional[bool] = True
    exclude_from_detail: Optional[bool] = True
    exclude_from_create: Optional[bool] = True
    exclude_from_edit: Optional[bool] = True
    searchable: Optional[bool] = False
    orderable: Optional[bool] = False
```

```
class User(MyModelView):
    fields = [
        Employee.id,
        Employee.login,
        PasswordField("password"),
        Employee.role, #some reltaion
        Employee.notes, #another relation
    ]
```
![image](https://user-images.githubusercontent.com/105509043/228618711-69c95ca1-0735-4da2-8633-723f0c534e84.png)

**Comment by MatsiukMykola** [comment]
1. try override __call__ of class
2. never store passwords opened, use hash + salt

**Comment by Ilya-Green** [comment]
1. I overrided, its looks like it has no effect. Or maybe i made something wrong
```
class UserView(MyModelView):
    def __call__(self, *args, **kwargs):
        return 1 #just for the test
```
I did not find an example of its usage in dependences.
2. Yeah, sure, but it wont solve this problem because someone can decrypt hash key by knowing they own password. Even if i will use salt, i must store it somewhere for every user. Anyway i'd like to figure out how hide sensitive fields because it too often needed.

**Comment by Ilya-Green** [comment]
Thank you. I find a solution.
I've found out that it is select2 method by uvicorn output:
`INFO:     127.0.0.1:14668 - "GET /api/user?skip=0&limit=20&select2=true`

So i overrided it. Just add PasswordField in isinstance:
```
class UserView(MyModelView):
    async def select2_result(self, obj: Any, request: Request) -> str:
        template_str = (
            "<span>{%for col in fields %}{%if obj[col]%}<strong>{{col}}:"
            " </strong>{{obj[col]}} {%endif%}{%endfor%}</span>"
        )
        fields = [
            field.name
            for field in self.fields
            if not isinstance(field, (RelationField, FileField, PasswordField))
        ]
        return Template(template_str, autoescape=True).render(obj=obj, fields=fields)
```
But it would also great to understand how to hide some columns depending on access rights. For now i see functionality for customize only for all users.

**Comment by jowilf** [comment]
> Even if i try to restrict field as much as possible it displays information in relation field of other view

You need to override [ModelView.select2_result](https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseModelView.select2_result) and/or [ModelView.select2_selection](https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseModelView.select2_selection) to customize the select2 rendering for relation fields. You can refer to this [example](https://github.com/jowilf/starlette-admin-demo/blob/9406c6908f6e89f953003bcafc4883dd732496c1/app/sqla/views.py#L17). I will add this information to the documentation.

> But it would also great to understand how to hide some columns depending on access rights. For now i see functionality for customize only for all users.

Right now it's not possible to do that with configuration. 

A possible workaround is to override the `serialize_value` function and return hidden information. 
```python
@dataclass
class PasswordField(StringField):
    
    async def serialize_value(
        self, request: Request, value: Any, action: RequestAction
    ) -> Any:
        if not request.state.user.has_role('admin'):
            return "******"
        return super().serialize_value(request, value, action)
```

But you can also override [ModelView._extract_fields](https://github.com/jowilf/starlette-admin/blob/0789b9495d5b50132c0082724aab07daee0ca77e/starlette_admin/views.py#L617) for custom logic
