### ISSUE TITLE
Enhancement: beanie support

### ISSUE THREAD

**Issue by opaniagu** [jowilf/starlette-admin#163]
did you start integrating beanie? do you have a possible date? I use benie because it allows me to create class dynamically with create_model (pydantic). thank you in advanced

**Comment by jowilf** [comment]
I cannot commit to a specific timeline for implementing Beanie support, but you could extend the BaseModelView to create a custom view that works with Beanie while waiting for official support.

Documentation: https://jowilf.github.io/starlette-admin/advanced/base-model-view/
Example code: https://github.com/jowilf/starlette-admin/tree/main/examples/custom-backend

**Comment by opaniagu** [comment]
Can you help/support me if I start developing the beanie support?

**Comment by opaniagu** [comment]
I sent a PR w/ beanie support
