### ISSUE TITLE
Bug: `CustomField` doesn't inherit class attributes for templates

### ISSUE THREAD

**Issue by mrharpo** [jowilf/starlette-admin#172]
**Describe the bug**
[Following the examples in the docs](https://jowilf.github.io/starlette-admin/advanced/custom-field/), `class CustomField` does not use templates that are defined as class attributes.

**To Reproduce**
Adapting from [examples/auth/view.py](https://github.com/jowilf/starlette-admin/blob/main/examples/auth/view.py)

```python3
from starlette_admin import BaseField
from starlette_admin.contrib.sqla import ModelView
from dataclasses import dataclass

@dataclass
class CustomField(BaseField):
    render_function_key: str = "mycustomkey"
    form_template: str = "forms/custom.html"
    display_template = "displays/custom.html"

class ArticleView(ModelView):
    fields = [
        "id",
        "title",
        "body",
        "status",
        CustomField(
            "title",
            label="Custom Title"
        )
    ]
```

##### templates/displays/custom.html

```html
<span>Hello {{data}}</span>
```

#### Expected results

The detail page should show `Hello {{data}}`

#### Actual results

The detail page shows `{{data}}`

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.8.0
 - ORM/ODMs: SQLModel, SQLAlchemy

**Additional context**

### Passing variables

The templates are correctly rendered when passing them into `CustomField`:

```python3
class ArticleView(ModelView):
    fields = [
        "id",
        "title",
        "body",
        "status",
        CustomField(
            "title",
            label="Custom Title",
            display_template="displays/custom.html",
            form_template="forms/custom.html",
        ),
    ]
```

`render_function_key` works as expected when defined as a class attribute, or passed into the instance.

**Comment by jowilf** [comment]
By default `dataclasses.asdict`  function is used to serialize fields. it seems to ignore the default value of non-annotated attributes. I have updated the [documentation](https://jowilf.github.io/starlette-admin/advanced/custom-field/).
