### ISSUE TITLE
export csv with utf-8 format incorrect

### ISSUE THREAD

**Issue by code4rain** [jowilf/starlette-admin#18]
For the datatable's export to csv, it has some problem with utf-8.
please refer: https://datatables.net/forums/discussion/37150/buttons-export-to-csv-doesnt-seem-to-take-charset-setting-into-account
could you update button with `charset: 'utf-8',`

**Comment by jowilf** [comment]
Hello @code4rain,
Please can you describe the exact problem you are facing with starlette-admin and add a minimum example?
And then I can be sure that adding `charset: utf-8`  solved it

**Comment by code4rain** [comment]
Hello, @jowilf 
I used Korean Name for username "김철수", then export CSV and open it via "Microsoft Excel" has some problem to show the username.
But I found the exported csv file seems to fine with `"`. It is due to Excel's encoding issue. I think.
Sorry for inconveniencing to you.

**Comment by jowilf** [comment]
Hello @code4rain,
Did you try to export directly to Excel ? 

> Hello, @jowilf I used Korean Name for username "김철수", then export CSV and open it via "Microsoft Excel" has some problem to show the username. But I found the exported csv file seems to fine with `"`. It is due to Excel's encoding issue. I think. Sorry for inconveniencing to you.

**Comment by code4rain** [comment]
Hello, @jowilf 
I try to export CSV and open it with Excel.
For the exporting excel, it works fine.

**Comment by jowilf** [comment]
> Hello, @jowilf 
> I try to export CSV and open it with Excel.
> For the exporting excel, it works fine.

Ok nice
