### ISSUE TITLE
Bug: 303 redirects at login screen

### ISSUE THREAD

**Issue by mixartemev** [jowilf/starlette-admin#182]
**Describe the bug**
Unable to see logo (from statics dir) at login screen, and also 1 of scripts (`js.cookie.min.js`) is not in allowed paths in `AuthMiddleware`.
<img width="585" alt="Screenshot 2566-05-04 at 16 48 33" src="https://user-images.githubusercontent.com/5181924/236230563-a9300b22-4375-41e9-9b7c-6b940acd36d0.png">

**To Reproduce**
Set `statics_dir` and put login_logo in this dir.
<img width="565" alt="Screenshot 2566-05-04 at 16 56 05" src="https://user-images.githubusercontent.com/5181924/236230638-56254751-a01a-43c2-ad01-76746367ee79.png">

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.8.1
 - ORM/ODMs: SQLAlchemy

**Comment by jowilf** [comment]
Fix in #187 & #183
