### ISSUE TITLE
FEAT: Add description to Field and display in create/edit forms

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [jowilf/starlette-admin#20]
Thank you _so_ much for this library! I've been watching sqladmin for a while to see if it has support for everything I need but this is already ready to go.

Flask-admin allows you to specify field descriptions for use in the form modals. It would be great to see that here too

**Comment by jowilf** [comment]
Hello @rafmagns-skepa-dreag,
Thanks for your interest and your kind comment.

Maybe you are looking for **help_text** option (not yet documented)

```python
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from starlette.applications import Starlette
from starlette_admin import StringField
from starlette_admin.contrib.sqla import Admin, ModelView

Base = declarative_base()
engine = create_engine("sqlite:///test.db", connect_args={"check_same_thread": False})


class Post(Base):
    __tablename__ = "posts"

    id = Column(Integer, primary_key=True)
    title = Column(String)


class PostView(ModelView, model=Post):
    fields = ["id", StringField("title", help_text="Your description here")]


Base.metadata.create_all(engine)
app = Starlette()

admin = Admin(engine)
admin.add_view(PostView)
admin.mount_to(app)
```

This is the result

![Screenshot from 2022-10-27 05-32-51](https://user-images.githubusercontent.com/31705179/198194399-4161fa3c-deb3-49d6-81d5-0829df23f351.png)

**Comment by rafmagns-skepa-dreag** [comment]
oh yes that would seem to do the trick! thank you!

**Comment by hasansezertasan** [comment]
I really love this module. 😍 

Let's say that I have a model like this:

```python
class Post(Base):
    id: Mapped[int]
    title: Mapped[str]
    content: Mapped[str]
```

---

In a Flask View, I would have to do this:

```python
class PostView(ModelView):
    column_list = [
        "id",
        "title",
    ]
    # The columns I want to include in the list view
    column_details_list = [
        "id",
        "title",
        "content",
    ]
    # The columns I want to include in the details view
    column_labels = {
        "id": "ID",
        "title": "Title",
        "content": "Content",
    }
    # The labels for the columns
    column_description = {
        "id": "ID of the record.",
        "title": "Your title here",
        "content": "Your content here",
    }
    # The descriptions for the columns
```

I don't know how to exclude from edit view in Flask Admin.

---

In Starlette Admin, I don't have to seperate related things. I can just group every configuration like this:

```python
class PostView(ModelView):
    fields = [
        IntegerField(
            name="id",
            label="ID",
            help_text="ID of the record.",
            read_only=True,
        ),
        StringField(
            "title",
            help_text="Your title here",
            exclude_from_edit=True,
        ),
        TextareaField(
            "content",
            help_text="Your content here",
            exclude_from_list=True,
        ),
    ]
```

In addition, we have these parameters if you don't want to use `BaseField` subclasses: `exclude_fields_from_create`, `exclude_fields_from_detail`, `exclude_fields_from_edit`, `exclude_fields_from_list`. You can use `exclude_fields_from_create` to do what it says...

Almost everything in Starlette Admin is easly overridable and configurable. Back in days when I discovered FastAPI, I switched my backend projects to FastAPI from Flask. I'm doing the same for my admin panels which I used Flask Admni for most of the time.
