### ISSUE TITLE
Question: How to add aggregate column to list view?

### ISSUE THREAD

**Issue by mixartemev** [jowilf/starlette-admin#219]
For example: "Comments count" column in Posts list view,
but **with no retreiving all relative Comments, just one `count(comments)` number for each post**.

**Comment by jowilf** [comment]
You can achieve this by creating a custom field and overriding [parse_obj](https://jowilf.github.io/starlette-admin/api/fields/#starlette_admin.fields.BaseField.parse_obj). An example can be found here -> 
https://github.com/jowilf/starlette-admin-demo/blob/a94eac84e58d150efddac6ecc6f1e4a3ba14cf8c/app/sqla/fields.py#L24

you can then access the SQLAlchemy session and perform your own queries. 

Here, A modified version of the example that perform a count query

```py
class CommentCounterField(StringField):
    """
    Example of field not tied to model attributes

    This fields will count the number of comments a user has made.

    It's important to exclude this fields from create and edit
    """

    async def parse_obj(self, request: Request, obj: Any) -> Any:
        assert isinstance(obj, User)
        session: Session = request.state.session
        stmt = select(func.count(Comment.pk)).where(Comment.user_id == obj.id)
        return session.execute(stmt).scalar_one()
```
