### ISSUE TITLE
Enhancement: Add a "show all rows" option

### ISSUE THREAD

**Issue by dfioravanti** [jowilf/starlette-admin#235]
**Is your feature request related to a problem? Please describe.**
In this list there is no option to choose "show me all the rows"

<img width="240" alt="Screenshot 2023-07-11 at 09 05 33" src="https://github.com/jowilf/starlette-admin/assets/115795/39ed84ce-e7bf-4d28-9ae1-7007a18d7130">

The use case for this is that the export button exports only what is showed on the UI so de facto there is no way to export results with more than 100 rows.

**Describe the solution you'd like**
I would like to have the option show all the rows

**Describe alternatives you've considered**
For what I need (export all rows) one could just change the exporter the export everything but that feels a bit aggressive and I am sure it would annoy someone who relies on the fact that only parts are exported.

**Comment by jowilf** [comment]
You can use -1 in the page_size_options to display all rows  -> https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#pagination

**Comment by dfioravanti** [comment]
Ah cool, I did not realize that. If there is not good reason to not do so, why not make it possible by default? I doubt I am the only one that needs it.
