### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by xorwise** [jowilf/starlette-admin#267]
**Describe the bug**
I try to deploy my FastAPI project where I use starlette_admin as an admin panel. My host is based on a HTTPS secured domain, but starlette admin uses static files and scripts through HTTP and it cannot load on my website.

**To Reproduce**
Try to access admin panel on a HTTPS secured domain

**Environment (please complete the following information):**
 - Starlette-Admin version: [e.g. 0.3.2]
 - ORM/ODMs: [SQLAlchemy, PostgreSQL, FastAPI]

**Additional context**
![image](https://github.com/jowilf/starlette-admin/assets/81633779/cc1b217e-fddf-45a6-8fe8-f18031cd4b06)

**Comment by jowilf** [comment]
https://jowilf.github.io/starlette-admin/deployment/

**Comment by xorwise** [comment]
thanks

**Comment by xorwise** [comment]
Thank you for such a quick response. Do you know by any chance what
parameters should I use if I start my project with gunicorn?
