### ISSUE TITLE
Enhancement:  How can I add PT (Portuguese) support?

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#268]
I want to volunteer to add Portuguese translations for the UI. I can see EN, FR and RU are suporte in the I18nConfig class. I see that SUPPORTED_LOCALES = ["en", "fr", "ru"].  What are the steps for me to add a Portuguese version? Please point me at the steps and I will do it.  Thanks!

**Comment by jowilf** [comment]
Thank you for your interest! I will update the contribution docs with more info on the translation process. In the meantime, here are the key steps:

1.  Generate the Portuguese translation files:
```sh
./i18n/init.sh pt
```
2. Translate all the `msgstr` keys in the file: `./translations/pt/LC_MESSAGES/admin.po`
3. Add `pt` to the SUPPORTED_LOCALES list -> https://github.com/jowilf/starlette-admin/blob/7a2c3618c803f9112889d256fb86f3c411b0923f/starlette_admin/i18n.py#L12C1-L12C39
4. Add the corresponding file for each folder in `./statics/i18n/` (you can submit a PR without it but make sure to add at list this json key -> https://github.com/jowilf/starlette-admin/blob/7a2c3618c803f9112889d256fb86f3c411b0923f/starlette_admin/statics/i18n/dt/en.json#L167 in your ./statics/i18n/dt/pt.json

For reference, you can check this PR https://github.com/jowilf/starlette-admin/pull/201.
