### ISSUE TITLE
Enhancement:  Auth example should demonstrate how to get a reference to the database/session

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#269]
The auth example at https://github.com/jowilf/starlette-admin/blob/main/examples/auth/provider.py#L6 could/should be improved to show how to get the data from the database. In my case, the database where the Admin is running has a User entity, with fields for the JWT-based authentication already implemented by an existing back-end. I would like the Admin system to honor the same login mechanism.

An alternative would be to show in the docs how to perform this type of ad-hoc impl, showing how to get at the session/database for the current context/Request, since it is not passed in. Dependency Injection? Reach into the app etc?

Thanks.

**Comment by jowilf** [comment]
The current database session is available via the request state
https://github.com/jowilf/starlette-admin/blob/7a2c3618c803f9112889d256fb86f3c411b0923f/examples/custom_actions/models.py#L51

I agree, adding a note in the documentation would make it more clear

**Comment by hasansezertasan** [comment]
I think we can close this one.
