### ISSUE TITLE
Enhancement: RBAC (role based access control) or similar?

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#276]
In https://github.com/jowilf/starlette-admin/issues/274 I show a simple approach to filter out entities that do not belong to the same "tenant id" as the logged user. ADMINISTRATOR can only see entities that belong to his company (same "tenant id"), whereas SUPERUSER can see everything (like a Linux "root"). Unfortunately the approach is just a first cut, being naive. If a URL is carefully crafted, one ADMINISTRATOR can probably visit entities of a different "tenant id", effectively escalating privileges to SUPERUSER (a SUPERUSER is an Admin for all tenants).

Is there a good orthogonal way to add RBAC (Role Based Access Control) to forms/areas of starlet-admin? I want to differentiate:

1. SUPERUSER: like root in Linux. Can manage all tenants, register a Company etc.Full Admin.
2. ADMINISTRATOR: He is powerful, but just in his own Company. Only see/edits an entity when its tenant_id is just like his own. Can't add Companies but can add Users in his own Company. Admin for his Company.
3. ANALYST: He can do things like create/edit Tasks, assign Tasks to users etc. All in his own Company.  Less powerful than an ADMINISTRATOR. Can't add Users like a TECHNICIAN. Admin for Tasks and Task Items.
4. TECHNICIAN: Can complete tasks, refuse tasks, add Task Items, Cannot create tasks like an ANALYST. Can only perform limited actions and limited browsing in the Admin UI.

The logged user has a Role field (an enum), which is one of the values above. How can I map which roles can go to which endpoints/templates in starlet-admin? Is there an extra package I need to install?  Maybe a decorator somewhere? 

Thanks for listening!

**Comment by jowilf** [comment]
This is already possible. Check the documentation here ->https://jowilf.github.io/starlette-admin/tutorial/authentication/#authorization
