### ISSUE TITLE
Enhancement: specialize fields using existing ones should be easier and better documented

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#277]
I have a database field that is an email address. I see that you have one such custom field: https://jowilf.github.io/starlette-admin/api/fields/#starlette_admin.fields.EmailField

However, reading https://jowilf.github.io/starlette-admin/advanced/custom-field/#list-rendering I get the impression I must write a JS function? This feels too complicated just for a simple mapping. Maybe the documentation could explain how to easily specialize the type of a field used in the GUI?

Why not support something like:

```
class UserAdmin(ModelView):
    fields = [User.doc_type, User.doc_code, User.linkedIn, User.name, User.email, User.phone, User.role, User.company, User.created_at]
    searchable_fields = [User.name, User.email, User.phone, User.doc_code]
    sortable_fields = [User.name, User.email, User.doc_code]
    exclude_fields_from_create = [User.created_at, User.updated_at]
    exclude_fields_from_edit = [User.created_at]
    field_specializations: { "email": starlette_admin.fields.EmailField, "phone": starlette_admin.fields.PhoneField, "linkedIn": starlette_admin.fields.URLField}
```

That is just an idea. Maybe there are smarter/simpler ones.

Thanks for listening.

**Comment by jowilf** [comment]
You can directly use a field in your fields list ([doc](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#fields)

Here is an example in the demo -> https://github.com/jowilf/starlette-admin-demo/blob/a94eac84e58d150efddac6ecc6f1e4a3ba14cf8c/app/sqla/views.py#L22
