### ISSUE TITLE
Bug: EDIT, relationship field is not displayed as per __admin_repr__

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#279]
**Describe the bug**
In the EDIT form, a "relationship" entity is displayed with a text representation that does not honor ```__admin_repr__```

**To Reproduce**
I have a User entity and a Company entity. When editing a user (click the pencil icon from the List View) the "company" property (a relationship with the Company table) displays like this:

<img width="1569" alt="image" src="https://github.com/jowilf/starlette-admin/assets/1507221/5b65e820-d5b0-4098-9dc4-5db5507620cf">

Basically these are all the field/columns. However, in models.py, the Company entity does override its UI/admin representation:

```
    def __admin_repr__(self, _):
        return self.name
```

which indeed is honoured in other places:

<img width="655" alt="image" src="https://github.com/jowilf/starlette-admin/assets/1507221/be7e01b8-a964-40d4-b84a-a3d87974ee63">

Why isn't the same textual representation ```__admin_repr__``` used to show a Company when it is in a relationship field?

**Environment (please complete the following information):**
starlette-admin==0.11.1
starlette-admin[i18n]==0.11.1
asyncpg==0.28.0
psycopg2==2.9.6

**Additional context**
No further info. I can try to cook aflui blown example if needed.

**Comment by jowilf** [comment]
The edit/create form show a select2 widget, to customize the rendering you need to override [`__admin_select2_repr__`](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#__admin_select2_repr__)
