### ISSUE TITLE
Enhancement:  hook to  compute entity attributes on NEW/save & EDIT/save?

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#287]
In the legacy system where I am trying to plug starlet-admin, the id field of every entity is computed with ```cuid.cuid()```. Therefore, I need the id field to be computed/assigned "just in time" (save button on NEW, but not on EDIT).

I also have fields such as  ```modified_at``` (a date) which store the date the entity was last modified. Therefore, I need it to be computed/assigned "just in time" (save button on EDIT, but not on NEW).

I can't find hooks for doing these things. Pardon in advance if I misread the docs. Thanks for listening !

**Comment by sglebs** [comment]
For the record, I have already tried this:

```
    async def create(self, request, data):
        extended_data = data.copy()
        extended_data["id"] = "123"  # normally we use cuid.cuid()
        extended_data["company_id"] = "cljyc6flm00001p1x3v55crqc" # normally the same as the logged user's
        return await super().create(request, extended_data)
```

but I still get this:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "id" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (null, 2023-09-02 11:53:09.73658-03, null, null, f, null, SUPERADMIN, null, null, null, m, m@m.com, 345, CPF, 34543543543, null, null, null, null, null, null, null, null, null, null, t, t).

```

**Comment by sglebs** [comment]
The problem is that this line in the super() method, ```obj = await self._populate_obj(request, self.model(), data)``` , actually skips attributes that are not listed as user-editable. That is unfortunate. I may have to plug my attires in AFTER calling super().

**Comment by jowilf** [comment]
using hook functions would be a great way to handle this. I will work on it (feel free also to submit a PR). But you can also achieve this by:

- using sqlalchemy default functions
- using read only field and then override the create method to set your id. (you don't need to  make a copy) [#see](https://github.com/jowilf/starlette-admin/discussions/240#discussioncomment-6534567)
```py
fields = [IntegerField("id", read_only=True)]
```
Also, primary keys are excluded by default from edit and create, so you need to set `form_include_pk=True` in your [ModelView](https://jowilf.github.io/starlette-admin/api/views/?h=form_inc#starlette_admin.views.BaseModelView)

**Comment by sglebs** [comment]
Thanks. I was coding this feature:

```
    computed_fields: Sequence[str] = []  # Workaround for
```

This attribute would allow me to say which ones are computed. Overriding ```_populate_obj``` I could make it respect the computed ones, even if not present in the form.

I think I will pause, backtrack and try your suggestion.

**Comment by sglebs** [comment]
This worked:

```
    id = Column(Text, primary_key=True, default=cuid)
    updated_at = Column(TIMESTAMP(timezone=True, precision=3), nullable=False,  onupdate=datetime.datetime.utcnow, default=datetime.datetime.utcnow)
```

Thanks for the suggestion!
