### ISSUE TITLE
Bug: ModelView does not take detail_template as parameter.

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#295]
**Describe the bug**
ModelView does not take ```detail_template``` as parameter.

**To Reproduce**
Try to instantiate a ModelView or a subclass and try to override ```detail_template``` passing it as parameter to the constructor. You can't.

Subclasses should still take in the same configurability found in their parent class constructor.

**Environment (please complete the following information):**
starlette-admin==0.11.1
databases==0.7.0
sqlalchemy
asyncpg==0.28.0
psycopg2==2.9.6
aiosqlite>=0.17.0
alembic==1.11.3

**Additional context**

I was working on https://github.com/jowilf/starlette-admin/issues/294

**Comment by jowilf** [comment]
ModelView doesn't take detail_template as a parameter but you can customize it by overriding the class variable. Here is the [documentation](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#templates) and here is an [example](https://github.com/jowilf/starlette-admin-demo/blob/a94eac84e58d150efddac6ecc6f1e4a3ba14cf8c/app/sqla/views.py#L58)
