### ISSUE TITLE
Enable sub properties of relationships to appear as columns

### ISSUE THREAD

**Issue by samearcher** [jowilf/starlette-admin#309]
### Discussed in https://github.com/jowilf/starlette-admin/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **samearcher** September 25, 2023</sup>
Hi,

I have a relationship, "mat_class" of my table, "A1_A3_Data", as follows:

```
class A1_A3_Data(A1_A3_Data_Base, ActiveRecordMixin, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    mat_class: Optional[Material_Class] = Relationship(back_populates="a1_a3_data")
```
This is in relationship (Many to one) with the Material_Class table:

```
class Material_Class(Material_Class_Base, ActiveRecordMixin, table=True):
    description: str = Field(min_length=3, max_length=200, unique=True)
    id: Optional[int] = Field(default=None, primary_key=True)
    a1_a3_data: List["A1_A3_Data"] = Relationship(back_populates="mat_class")
```

I'd like to be able to display (and sort) a column representing the mat_class description field as follows:

```
class A1_A3_Data_View(BaseModelView):
    fields = [
        A1_A3_Data.mat_class.description,
        "sheet_title",
        etc, etc
]
```

At the moment this gives the following error:

AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with A1_A3_Data.mat_class has an attribute 'description'

I think this is because it's referencing the Class rather than the instances of the class?

Thanks</div>

**Comment by jowilf** [comment]
This was previously discussed in #240 
Better support for InlineModels (at least for SQLAlchemy) will solve this. but It will probably be something like:

```py
fields = [
        "mat_class.description",
        "sheet_title",
        etc, etc
]
````

**Comment by samearcher** [comment]
Thanks @jowilf . One of the reasons I want to include the mat_class description is so that I can sort/filter on this column. At the moment I can include A1_A3_data.mat_class as a column since it's a column in the A1_A3_data table. However, this column is not sortable or filterable in starlette_admin.

**Comment by hasansezertasan** [comment]
> This was previously discussed in #240 Better support for InlineModels (at least for SQLAlchemy) will solve this. but It will probably be something like:
> 
> ```python
> fields = [
>         "mat_class.description",
>         "sheet_title",
>         etc, etc
> ]
> ```

Do we have any progress on it?
