### ISSUE TITLE
DataTables issue

### ISSUE THREAD

**Issue by mariofix** [jowilf/starlette-admin#31]
Hi, I stumbled upon your app and it's very impressive.
I've been testing it migrating from another admin and is almost direct.
I have one issue so far, and it's with the fields parameter

```python
class UserAdmin(ModelView):
    fields = [User.login]

app.admin_site.add_view(UserAdmin(User))
```
I get a DataTables warning (it's pretty anoying)
> DataTables warning: table id=dt - Requested unknown parameter 'DT_RowId' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

if I remove the fields parameter in UserAdmin, it works like a charm.
Is there a way to **disable** the ajax load function for datatables?

**Comment by jowilf** [comment]
Hello @mariofix,
Glad you find it impressive,

When you customize fields you need to provide

**Comment by mariofix** [comment]
Excellent, that fixed the warning. Thank you! 

Although I believe the PK should be included no matter what, or at least a way to disable the warning.

Is there a way to disable the ajax call for the table?

**Comment by jowilf** [comment]
Hello @mariofix ,
May I ask why you need to disable the ajax call? because the list is rendered via ajax call.
You don't want to use the list page?
If you don't want the primary key in your list page, you can [exclude it](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#exclusions)

**Comment by mariofix** [comment]
Hi! Thanks for your quick reply and I'm sorry, it appears I'm not making myself very clear.

I no not wish no exclude the PK, I only believe that the PK should not be optional for that type of view.
If someone make the same mistake I did, they would take quite a few to get to the answer, because the behaviour is pretty weird:
If I get the warning, it goes away if I include the PK in the fields parameter, fair enough
If the PK is not present, I get the warning but I still get to view and edit the record via the action icons, so DataTables shouldn't complaint, because the PK is present.

Regarding DataTables, for stuff like this I've never had a pretty good experience with the way DT makes the ajax calls and prepares the data, so I try to avoid DT as much as possible.
Besides, i'm still not there (I'm migrating from sqladmin) but I will need to modify the queryset at some point, I can't imagine that mess with the DataTables ajax calls.

I'm more than happy to code that, but not if you are not considering it or you already have something to that effect.
Best regards

**Comment by jowilf** [comment]
Hello,
I think it's very clear now,
To resume:
- The warning can be solved by returning the primary key to Datatables even if it not specify in fields ( i think this is a bug, should be fixed)
- Add support for  `list_query` and `count_query` to ease the query customization for SQLAlchemy (and maybe find similar solution for others backend)

wdyt?

**Comment by mariofix** [comment]
Superb!
How can I help?

**Comment by jowilf** [comment]
> Superb! How can I help?

Hello @mariofix,
you have already done well by reporting this issue, thank you.

I will close this issue now and open two others issues
