### ISSUE TITLE
Suggestion for URLs

### ISSUE THREAD

**Issue by mariofix** [jowilf/starlette-admin#32]
Hello, I'm trying your app and I noticed it creates a few routes `/statics`, `/api/{identity}`, they get added at the root.

>INFO:     127.0.0.1:41598 - "GET /user/list HTTP/1.1" 200 OK
>INFO:     127.0.0.1:41598 - "GET /api/user?skip=0&limit=10 HTTP/1.1" 200 OK
>INFO:     127.0.0.1:56438 - "GET /api/user?skip=0&limit=10 HTTP/1.1" 200 OK

I believe they should be added after `base_url=/admin` so the URL always has /admin prepended.
I was about to make the fork and then the PR but I noticed you're about lo launch a new release, are you considering making this modification? I can make it if you didn't consider it for the new release.

**Comment by jowilf** [comment]
Hello,
starlette-admin create a mounted app into your original app with `base_url` as base root path. 

It won't be visible in log due to this issue in starlette itself ->
https://github.com/encode/starlette/issues/1336

Thank you.
