### ISSUE TITLE
Enhancement: How to add custom action toolbar icons/buttons in List View

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#324]
**Is your feature request related to a problem? Please describe.**

In the list view one can see 2 icons on each element: an eye (inspector/details) and a paper/pencil (edit the entity).
It is desirable to add more actions as buttons here. For example DELETE could be trash can and work as a shortcut to "With Selected => Delete", saving clicks. It could also be used to go to custom action pages for that entity ("import a props file into this entity", etc etc).

**Describe the solution you'd like**
Be able to plug more action buttons into the List View, defining their icon, tooltip string and action function/method.

**Describe alternatives you've considered**
I looked at the documentation and could not find how to add an extra one. Maybe it is already doable and just the documentation that needs fixing. Or perhaps I need new glasses :-)

I could also dig into the sources and reverse engineer how you do the existing ones. Last resort.

**Additional context**
None.

**Comment by hasansezertasan** [comment]
I believe it's here: [Actions - Starlette Admin](https://jowilf.github.io/starlette-admin/api/actions/)
