### ISSUE TITLE
Enhancement: Save "show/hide" state in local-storage

### ISSUE THREAD

**Issue by ManiMozaffar** [jowilf/starlette-admin#332]
**Is your feature request related to a problem? Please describe.**
When I click on "show" a column, or hide, as i refresh my page, my setting is gone. I argue that from the point of design, those visualization preference should be cached in Local Storage, and then shown to user

**Describe the solution you'd like**
Maybe map configuration to url, in local storage? under a key?

**Describe alternatives you've considered**
Nothing really :D

**Additional context**
None

**Comment by jowilf** [comment]
Fixed in #298, will be released in 0.12.0
