### ISSUE TITLE
Move default row count and pagination to the top of the table

### ISSUE THREAD

**Issue by live-act** [jowilf/starlette-admin#334]
**Is your feature request related to a problem? Please describe.**
Move the default row count and pagiantion to the the top of the table - similar to other more modern approach as shown in the `flask-appbuilder` example below

![image](https://github.com/jowilf/starlette-admin/assets/30543352/a4c617ff-d240-43da-8fcc-81831fb23b7b)

**Describe the solution you'd like**
For large tables (100K+ ), it makes more sense for users have a sense of how many records that they see and then apply filter to check what records need to be kept in viewing. The user experience is pretty bad when the row count and page number are down in the botton. 

**Describe alternatives you've considered**
I have been using flask-appbuilder for building admin panels but I would like to try using starlette-admin in a new project.

**Comment by hasansezertasan** [comment]
A better option would be adding an option to pick a location for the bar when defining an instance and maybe in the future it would be configurable by the users, like dark/light theme which is like a good to have for a web page.

**Comment by live-act** [comment]
Thank you @hasansezertasan ..! I will wait for 0.12.0 then. Appreciate your help.

**Comment by hasansezertasan** [comment]
You're welcome, can you close this issue?

**Comment by live-act** [comment]
Yes, of course. Thank you

**Comment by jowilf** [comment]
Thank you for your help @hasansezertasan.

> I'm planning to create a pydantic model to validate datatables_options attribute. How is that sounds like @jowilf, do you think we need that?

I think it's necessary, we can't make `pydantic` a required dependency just to validate the `datatables_options`

**Comment by hasansezertasan** [comment]
> Thank you for your help @hasansezertasan.
> 
> > I'm planning to create a pydantic model to validate datatables_options attribute. How is that sounds like @jowilf, do you think we need that?
> 
> I think it's necessary, we can't make `pydantic` a required dependency just to validate the `datatables_options`

Oh, I'm confused. Should we have a validator for `datatables_options` or not?

**Comment by jowilf** [comment]
> Oh, I'm confused. Should we have a validator for datatables_options or not?

Sorry i was saying `it's not necessary`

**Comment by hasansezertasan** [comment]
Thank you for your response.
