### ISSUE TITLE
Enhancement: Flask Admin like `can_edit`, `can_create`, `can_delete` and `can_view_details` features

### ISSUE THREAD

**Issue by hasansezertasan** [jowilf/starlette-admin#339]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to configure editing, creating, deleting and viewing details. 

**Describe the solution you'd like**
If can_edit is set to `False`, we should remove the `Edit` button. I'm not sure if we should contrcut the endpoint for that progress or not.

**Describe alternatives you've considered**
[Flask Admin](https://flask-admin.readthedocs.io/en/latest/introduction/#modelview-configuration-attributes) has this feature, which probably would be a great reference.

**Comment by jowilf** [comment]
This is already supported, take a look at -> https://jowilf.github.io/starlette-admin/tutorial/authentication/#for-modelview & https://github.com/jowilf/starlette-admin/tree/main/examples/auth

**Comment by hasansezertasan** [comment]
> This is already supported, take a look at -> https://jowilf.github.io/starlette-admin/tutorial/authentication/#for-modelview & https://github.com/jowilf/starlette-admin/tree/main/examples/auth

Ah geeze, my bad, thank you.
