### ISSUE TITLE
Enhancement: Translation / Locale support for table names.

### ISSUE THREAD

**Issue by hasansezertasan** [jowilf/starlette-admin#357]
**Is your feature request related to a problem? Please describe.**
I'm building my admin interface with Starlette Admin, which is awesome. I recently opened a merged PR at #330 to add Turkish Language support but many of my table names, view names are in English name but some of my users will be speaking English or other Languages.

**Describe the solution you'd like**
Maybe we can create a locale system to distinguish user's selected language and, with a can create a dictionary map to set view and column names in different languages.

A simple example could be like this:

```python
class CompanyView(ModelView):
    locale = {
        "en": {
            "view_label": "Companies",
            "view_name": "Company",
            "id": "ID",
            "name": "Name",
        },
        "tr": {
            "view_label": "Şirketler",
            "view_name": "Şirket",
            "id": "ID",
            "name": "İsim",
        },
        "fr": {
            "view_label": "Entreprises",
            "name": "Entreprise",
            "id": "ID",
            "name": "Nom",
        },
    }
    fields = [
        "id",
        "name",
        CollectionField(
            "status",
            fields=[
                IntegerField("id", read_only=True),
                StringField("name"),
            ],
            locale={
                "en": "status",
                "tr": "durum",
                "fr": "statut",
            }
        ),
    ]
```

**Describe alternatives you've considered**
I'm not considering any alternative, no pressure!

**Comment by jowilf** [comment]
The best approach is to set up [Babel](https://babel.pocoo.org/) in your project. You can get the current locale using [get_locale()](https://github.com/jowilf/starlette-admin/blob/f1bc6e927223458abcbe77d949222a5ef700af39/starlette_admin/i18n.py#L44).

**Comment by hasansezertasan** [comment]
Thank you for your help.

I haven't try that since it was simply an idea that could be usefull for users but looking at it again, using babel directly (without an abstraction layer inside the module) would be a great practice for the users.
