### ISSUE TITLE
Bug: STATICS DONT WORK ON THE SERVER via coolify and custom nginx.conf

### ISSUE THREAD

**Issue by OzodbekUSTECH** [jowilf/starlette-admin#424]
**Describe the bug**
I am deploying fastapi project via coolify and docker. Everything works except for statics, as if nginx cant find statics. I tried different ways and found one solution, changed the src for statics in html files(../statics/etc)- like that. And finally it works, but i would like to get better way to solve it out.

**Environment (please complete the following information):**
 - starlette-admin==0.12.2
 - SQLAlchemy==2.0.20

**Comment by OzodbekUSTECH** [comment]
> I mean, it doesn't look like a Starlette Admin issue. I'm using DO Droplet with Docker containers and it works great! WTYT @jowilf?

I got an error, its about mixed content. I deployed project on the server via docker and nginx + coolify. And in links(html) there is http://domain. However my server has HTTPS://

How to get https:// by using request.url_for???

**Comment by jowilf** [comment]
Thank you, @hasansezertasan, for your help. 

@OzodbekUSTECH, take a look at https://jowilf.github.io/starlette-admin/deployment/
