### ISSUE TITLE
Enhancement: New Field Recommendation: Jodit Editor

### ISSUE THREAD

**Issue by hasansezertasan** [jowilf/starlette-admin#439]
[Jodit Editor](https://xdsoft.net/jodit/): Open Source WYSIWYG editor written in pure TypeScript

It has CDN support and is initialized by a single line of JavaScript.

I'm planning to implement a field that uses Jodit Editor. I have a lot more fields in mind.

Should I implement it and open a PR?

**Comment by hasansezertasan** [comment]
@jowilf As I said, I hava a lot more fields in mind, so you might think that creating a third party package like 'starlette-admin-fields' is a better idea. If that will be the case would you mention and reference this hypothetical package in the documentation and readme and also help me build (I'm not sure how it would integrate with starlette-admin) it, just integration aspect is my blind spot.

**Comment by jowilf** [comment]
> @jowilf As I said, I have a lot more fields in mind, so you might think that creating a third-party package (something called 'starlette-admin-fields') is a better idea.

I agree. I also think that it's a better idea.

> If that is the case would you mention and reference this hypothetical package in the documentation and readme?

we can add a third-party packages section similar to https://www.starlette.io/third-party-packages/

**Comment by hasansezertasan** [comment]
> I agree. I also think that it's a better idea.

Great, how do we proceed from here? What should we do next?

> we can add a third-party packages section similar to https://www.starlette.io/third-party-packages/

Fantastic!

I believe we can add a parameter to the `BaseAdmin` class, something like `extra_template_loaders` and users can extend the templates folder with third-party-packages.

https://github.com/jowilf/starlette-admin/blob/769a85ffdcc3fbf0b2e9dff235678e88fa4128b4/starlette_admin/base.py#L191-L196

Example in mind:

```python
    def _setup_templates(self) -> None:
        templates = Jinja2Templates(self.templates_dir, extensions=["jinja2.ext.i18n"])
        templates.env.loader = ChoiceLoader(
            [
                FileSystemLoader(self.templates_dir),
                PackageLoader("starlette_admin", "templates"),
                *self.extra_template_loaders,
            ]
        )
        ...
```

And I think we can follow the same pattern with the `statics` folder.

I'm open to suggestions but this is the first way of doing this that popped into my mind.

**Comment by hasansezertasan** [comment]
Field Proposal:

`ModalField`, it's a text or a button, it shows a "modal", and fetches the content of the modal from the backend.

**Comment by hasansezertasan** [comment]
Field Proposal:

`CronEditorField`, think of something like the editor in this repo: [Marak/cron-editor: Visual Cron Editor - Edit and Create Cron Jobs With Ease](https://github.com/Marak/cron-editor) and be helpful for #433

**Comment by hasansezertasan** [comment]
@jowilf WDYT about https://github.com/jowilf/starlette-admin/issues/439#issuecomment-1870580099

**Comment by hasansezertasan** [comment]
Field Proposal:

Not exactly a proposal but just take a look at this project: cllen/flask-admin-tablefield

**Comment by hasansezertasan** [comment]
Field Proposal:

Not exactly a proposal but just take a look at this project: [artemShelest/flask-admin-subview](https://github.com/artemShelest/flask-admin-subview)

**Comment by hasansezertasan** [comment]
Field Proposal:

Not exactly a proposal but just take a look at this project: [nathancahill/Flask-Edits](https://github.com/nathancahill/flask-edits)

**Comment by hasansezertasan** [comment]
Field Proposals: this is not exactly a proposal but these projects are inspirational...

- [nathancahill/Flask-Edits](https://github.com/nathancahill/flask-edits)
- [artemShelest/flask-admin-subview](https://github.com/artemShelest/flask-admin-subview)
- [cllen/flask-admin-tablefield](https://github.com/cllen/flask-admin-tablefield)

**Comment by hasansezertasan** [comment]
I started to build a third-party package to cover these fields: [hasansezertasan/starlette-admin-fields: Extra fields to use with Starlette Admin](https://github.com/hasansezertasan/starlette-admin-fields)
