### ISSUE TITLE
Question: How to prevent SQLAlchemy from showing soft-deleted relational-records?

### ISSUE THREAD

**Issue by hasansezertasan** [jowilf/starlette-admin#468]
In this application, no delete action is taken immediately. Records to be deleted are marked with a column called "date_deleted" and will be deleted after a while. I managed to filter the deleted records from the list view and count query using `get_list_query` and `get_count_query` but I couldn't find a way to exclude these "marked" records from the `RelationalField`s.

In this image, we see the "Children" attribute with two relations:

![image](https://github.com/jowilf/starlette-admin/assets/13135006/b4b9c6e1-678e-4d2f-8b49-89e4c5f08f86)

But as you can see in this image, the child record with the id of 2 is deleted (marked), so it's not included in the list view...

![image](https://github.com/jowilf/starlette-admin/assets/13135006/797891ed-9f4a-4b01-898d-d9ac62e7eb91)

Here is an image from DB Browser for SQLite3:

![image](https://github.com/jowilf/starlette-admin/assets/13135006/dbabfc23-5228-41ed-9f51-6e27b6ed14f7)

As you can see, there is still a record but it's marked as "deleted". I can exclude these records from the list view and count query but `RelationField` still brings them.

Here is the code:

```python
import datetime
from typing import Any, List, Optional

from sqlalchemy import ForeignKey, create_engine, update
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, relationship
from sqlalchemy.sql import Select
from starlette.applications import Starlette
from starlette.requests import Request
from starlette_admin.contrib.sqla import Admin, ModelView


engine = create_engine("sqlite:///db.sqlite3", connect_args={"check_same_thread": False})


class Base(DeclarativeBase):
    pass


class ModelMixin:
    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
        index=True,
        unique=True,
    )
    date_created: Mapped[datetime.datetime] = mapped_column(
        default=datetime.datetime.utcnow,
        index=True,
    )
    date_updated: Mapped[datetime.datetime] = mapped_column(
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
        index=True,
    )
    date_deleted: Mapped[datetime.datetime | None]


class Parent(Base, ModelMixin):
    __tablename__ = "parent"
    name: Mapped[str]
    children: Mapped[list["Child"]] = relationship("Child", back_populates="parent")


class Child(Base, ModelMixin):
    __tablename__ = "child"
    name: Mapped[str]
    parent_id: Mapped[int] = mapped_column(ForeignKey("parent.id"))
    parent: Mapped["Parent"] = relationship("Parent", back_populates="children")


class ModelViewMixin(ModelView):
    async def delete(self, request: Request, pks: List[Any]) -> Optional[int]:
        session: Session = request.state.session
        utcnow = datetime.datetime.utcnow()
        query = (
            update(self.model)
            .filter(
                self.model.id.in_(pks),
            )
            .values(
                {
                    self.model.date_deleted: utcnow,
                },
            )
        )
        session.execute(query)
        session.commit()
        return len(pks)

    def get_list_query(self) -> Select:
        return super().get_list_query().filter(self.model.date_deleted.is_(None))

    def get_count_query(self) -> Select:
        return super().get_count_query().filter(self.model.date_deleted.is_(None))


class ParentView(ModelViewMixin):
    fields = ["id", "date_created", "date_updated", "name", "children"]
    exclude_fields_from_create = ["id", "date_created", "date_updated", "children"]


class ChildView(ModelViewMixin):
    fields = ["id", "date_created", "date_updated", "name", "parent"]
    exclude_fields_from_create = ["id", "date_created", "date_updated"]


Base.metadata.create_all(engine)

app = Starlette()
admin = Admin(engine, title="Soft Deletion")
admin.add_view(
    ParentView(
        model=Parent,
    ),
)
admin.add_view(
    ChildView(
        model=Child,
    ),
)
admin.mount_to(app)

```

One workaround I can think of is something like this:

```python
class Parent(Base, ModelMixin):
    __tablename__ = "parent"
    name: Mapped[str]
    children: Mapped[list["Child"]] = relationship(
        "Child",
        back_populates="parent",
        primaryjoin="and_(Child.parent_id == Parent.id, Child.date_deleted.is_(None))",
    )
```

Which is OK, if I didn't have 70 tables with tons of relations and all soft-deletable.

And there is also a requirement...

> "Admins should see those records before permanent deletion."

I'd rather write those `primaryjoin` conditions by hand but I believe we should have a solution for this.

---

Additionally, I checked the source code and searched for some code that I could override but couldn't find. It would be great if someone would tell me where to look. I believe I can come up with a solution.

**Comment by jowilf** [comment]
Take a look at -> https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#specifying-alternate-join-conditions

**Comment by hasansezertasan** [comment]
> Take a look at -> https://docs.sqlalchemy.org/en/20/orm/join_conditions.html#specifying-alternate-join-conditions

Thank you for your quick answer 🙏

I have already read that documentation and I implemented something similar at the end of the issue.

Here...

> One workaround I can think of is something like this:
> 
> ```python
> class Parent(Base, ModelMixin):
>     __tablename__ = "parent"
>     name: Mapped[str]
>     children: Mapped[list["Child"]] = relationship(
>         "Child",
>         back_populates="parent",
>         primaryjoin="and_(Child.parent_id == Parent.id, Child.date_deleted.is_(None))",
>     )
> ```

I was asking for an alternative solution that can help me dynamically update the query according to the user access.

**Comment by hasansezertasan** [comment]
Related issue from flask-admin repo: [Soft delete handlling · Issue #1941 · flask-admin/flask-admin](https://github.com/flask-admin/flask-admin/issues/1941)

**Comment by hasansezertasan** [comment]
> > "Admins should see those records before permanent deletion."

I was able to manage this with a non-starlette-admin-related workaround.

```python
class Parent(Base, ModelMixin):
    __tablename__ = "parent"
    name: Mapped[str]
    children: Mapped[list["Child"]] = relationship(
        "Child",
        back_populates="parent",
        primaryjoin="and_(Child.parent_id == Parent.id, Child.date_deleted.is_(None))",
    )
    deleted_children: Mapped[list["Child"]] = relationship(
        "Child",
        back_populates="parent",
        primaryjoin="and_(Child.parent_id == Parent.id, Child.date_deleted.isnot(None))",
    )
```

It was quite an annoying situation. I hope no one would need this.

For anyone who wants to know where to look, check these out:

https://github.com/jowilf/starlette-admin/blob/09e8ba3be497834330cf124e1dbe0119ba5212c7/starlette_admin/contrib/sqla/view.py#L277-L308

https://github.com/jowilf/starlette-admin/blob/09e8ba3be497834330cf124e1dbe0119ba5212c7/starlette_admin/contrib/sqla/view.py#L310-L347

https://github.com/jowilf/starlette-admin/blob/09e8ba3be497834330cf124e1dbe0119ba5212c7/starlette_admin/contrib/sqla/view.py#L361-L383

https://github.com/jowilf/starlette-admin/blob/09e8ba3be497834330cf124e1dbe0119ba5212c7/starlette_admin/contrib/sqla/view.py#L519-L543

Take a look at wherever you see a `RelationField` keywoard in `starlette_admin/contrib/sqla/view.py`
