### ISSUE TITLE
Bug: StopIteration when there is a table with a Primary key, which also is a Foreign Key

### ISSUE THREAD

**Issue by abinba** [jowilf/starlette-admin#481]
**Describe the bug**

After the update to 0.13.0, I detected an issue that when there is a table that has a single primary key, which is a foreign key, stalette-admin throws out `StopIteration` error.

Before the update, there hasn't been such error.

**To Reproduce**

Create a table that has a Primary Key, which additionally is a Foreign key with SQLAlchemy, for example:

```
class Account(BaseABC):
    __tablename__ = "account"

    account_id = sa.Column(sa.Integer, primary_key=True, index=True)
    username = sa.Column(sa.String, unique=True, index=True)
    is_active = sa.Column(sa.Boolean, default=True)


class UserSettings(BaseABC):
    __tablename__ = "user_settings"

    account_id = sa.Column(
        sa.Integer, sa.ForeignKey("account.account_id"), primary_key=True
    )
    account = relationship(
        "Account",
        backref="settings",
        cascade="all, delete-orphan",
        single_parent=True,
    )

    theme = sa.Column(sa.String(40), server_default="light")
```

And when adding the view of UserSettings model with starlette-admin:
```
admin.add_view(ModelView(UserSettings, label="User Settings"))
```
It results in the `StopIteration` error.

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.13.0
 - ORM/ODMs: SQLAlchemy
 - Python: 3.11

**Track trace**
```
  File "/home/abinba/PycharmProjects/funny-dolphine/src/app.py", line 9, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/abinba/PycharmProjects/funny-dolphine/src/web/factory.py", line 11, in create_app
    setup_admin(_app)
  File "/home/abinba/PycharmProjects/funny-dolphine/src/web/admin.py", line 50, in setup_admin
    admin.add_view(ModelView(UserSettings, label="User Settings"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abinba/PycharmProjects/funny-dolphine/venv/lib/python3.11/site-packages/starlette_admin/contrib/sqla/view.py", line 116, in __init__
    self.pk_field: BaseField = next(
                               ^^^^^
StopIteration
```

**Additional context**
I have been debugging it, and it seems that the problem is in this line:

`starlette_admin/contrib/sqla/view.py` (114-116)
```
self.pk_field: BaseField = next(
    f for f in self.fields if f.name == self.pk_attr
)
```
It iterates through the `fields`, but as `convert_fields_list()` function eliminates foreign key fields, it can't find the primary key.
In the previous version of `stalette_admin`, if I'm not mistaken, following was used to retrieve the primary key column:
```
self._pk_column: Column = next(iter(mapper.local_table.primary_key))
```
I can create a PR fixing the issue if you'd like.

**Comment by abinba** [comment]
I think that expected behavior can be divided into two cases in SQLAlchemy:

**1. Table has a field, which is both PK and FK and there IS NO relationship SQLAlchemy construct.**
```
class UserSettings(BaseABC):
    __tablename__ = "user_settings"

    account_id = sa.Column(
        sa.Integer, sa.ForeignKey("account.account_id"), primary_key=True
    )

    theme = sa.Column(sa.String(40), server_default="light")
```

**2. Table has a field, which is both PK and FK and there IS a relationship construct.**
```
class UserSettings(BaseABC):
    __tablename__ = "user_settings"

    account_id = sa.Column(
        sa.Integer, sa.ForeignKey("account.account_id"), primary_key=True
    )
    account = relationship(
        "Account",
        backref="settings",
        cascade="all, delete-orphan",
        single_parent=True,
    )

    theme = sa.Column(sa.String(40), server_default="light")
```

In the ideal case, `pk_field` should be assigned to be the `RelationField` in both cases, but I'm not yet sure if this is possible. I might still be misunderstanding something, please correct me if I'm wrong or if I'm thinking in the right direction.

**Comment by jowilf** [comment]
The issue is related to the `pk_field` which is used to [extract the primary key value from objects](https://github.com/jowilf/starlette-admin/blob/63948e34919d62556c66266e67a3f3ecdfa7af8d/starlette_admin/contrib/sqla/view.py#L605). The current implementation does not consider the possibility that the primary key may not be included in the fields list. To fix this, we can use a `StringField` for this special case since the value is only used to generate the edit, detail, ... URLs
