### ISSUE TITLE
Bug: unsafe to upgrade from 0.11.2 to 0.13.1 - relationship columns show as undefined

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#487]
**Describe the bug**

I have been trying to upgrade from 0.11.2 but bugs prevent me from doing so, for a long time. With 0.13.1 (and before) relationship columns display as "undefined", while in 0.11.2 they display fine, in blue, and as a hyperlink (lovely feature btw). I have been facing this problem since right after 0.11.2. For example, a User belongs to a Client, so a user has these fields:

```
    client_id = Column(ForeignKey('clients.id', ondelete='SET NULL', onupdate='CASCADE'))
    client = relationship('Client')
```

and the UserAdminView:

```
class UserAdminView(WorakaroundModelView):
    fields = [StringField("name"), EmailField("email"), StringField("legal_id"), User.role, User.client, User.created_at, User.updated_at]
    searchable_fields = [User.name, User.email, User.legal_id]
    sortable_fields = [User.name, User.email, User.legal_id, User.created_at, User.updated_at]
    exclude_fields_from_create = [User.created_at, User.updated_at]
    exclude_fields_from_edit = [User.created_at, User.updated_at]
    fields_default_sort = [("updated_at", True), ("created_at", True), "name"]
 
```

NOTE: WorakaroundModelView  is my own subclass to overcome bugs such as https://github.com/jowilf/starlette-admin/issues/356

In the List View, the CLIENT column will display: "undefined", in blue.

**To Reproduce**

Well, I just had to upgrade to see the problem above. It has always been like this since 0.11.2

**Environment (please complete the following information):**

   * Starlette-Admin version: 0.13.1
   * ORM/ODMs: SQLAlchemy, psycopg2-binary==2.9.9
   * SQLAlchemy-serializer==1.4.1

**Additional context**

ALL my relationship columns in ALL entities are having this problem.

**Comment by sglebs** [comment]
0.12.0 already has this bug. 0.11.2 does not.

**Comment by jowilf** [comment]
There have been some changes to the static JavaScript files. Try deleting your browser cache.

**Comment by sglebs** [comment]
Indeed. I opened it in Microsoft Edge - which I had never used to open the link - and the relationships display properly. Thanks!
