### ISSUE TITLE
Bug: With Text field (multiline) adds extra leading spaces every time I edit/save (no changes)

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#493]
**Describe the bug**

Before I was using StringField("uri") but now I want to have multilines text, so I use MyEntity.uri. However, after using the default field type like this, I noticed that if I edit&save with no changed, this field get an extra padding of spaces at the beginning. See how it is now:

<img width="496" alt="image" src="https://github.com/jowilf/starlette-admin/assets/1507221/b95f3cc4-7f8d-49e7-8ae9-a1b69521ea7f">

**To Reproduce**

```
class KnowledgeSource(Base):
    __tablename__ = 'knowledge_sources'
    uri = Column(Text)
```

In your ModelView:

```
fields = [ KnowledgeSource.uri]
```

**Environment (please complete the following information):**

   * Starlette-Admin version: 0.13.1
   * ORM/ODMs: SQLAlchemy, psycopg2-binary==2.9.9
   * SQLAlchemy-serializer==1.4.1

**Additional context**
I had not seen this bug in 0.11.2.

**Comment by rafmagns-skepa-dreag** [comment]
I am also seeing this issue on 0.13.1

**Comment by sglebs** [comment]
Any chance a patch release could be produced? This is a bit of a pain as is. Thanks!
