### ISSUE TITLE
Bug: Sorting custom fields descendingly gives error

### ISSUE THREAD

**Issue by omarmoo5** [jowilf/starlette-admin#511]
**Describe the bug**
Whenever i try to sort a custom field descendingly it gives an error.

**To Reproduce**
For example here in the demo example , the comments field of [users page](https://starlette-admin-demo.jowilf.com/admin/sqla/user/list).

If you tried to sort the comments counter field descendingly . it fails.

**Comment by Ilya-Green** [comment]
which one is comment field? can you provide screen?
if you mean relation field it bacuse it can't undarstand how to sort it, by which parametr.
One of possible solution is mat be editing helpers.py: def build_order_clauses: adding this to func:
`if attr_key == 'status': attr_key = 'status_id'`
but i suppose it will work only for hasone relations.

**Comment by Ilya-Green** [comment]
also i found this construction in [admin source code](https://github.com/jowilf/starlette-admin-demo), it can be solution:
```
class PostView(ModelView):
    fields = [
        "id",
        "publisher",
    ]
    sortable_field_mapping = {"publisher": User.full_name}
```

**Comment by Ilya-Green** [comment]
this is code of how this counter works:
class CommentCounterField(StringField):
    async def parse_obj(self, request: Request, obj: Any) -> Any:
        assert isinstance(obj, User)
        return len(obj.comments)
        
it just counts the number of comments and returns a number, but it seems it is not set by which parameter such a field should be sorted

**Comment by omarmoo5** [comment]
> this is code of how this counter works:
> 
> class CommentCounterField(StringField):
> 
>     async def parse_obj(self, request: Request, obj: Any) -> Any:
> 
>         assert isinstance(obj, User)
> 
>         return len(obj.comments)
> 
>         
> 
> it just counts the number of comments and returns a number, but it seems it is not set by which parameter such a field should be sorted

Thanks for your reply, Surprisingly it can sorts them ascendingly.
