### ISSUE TITLE
The live demo is down: `ERR_CONNECTION_REFUSED`

### ISSUE THREAD

**Issue by hasansezertasan** [jowilf/starlette-admin#513]
The live demo is down: `ERR_CONNECTION_REFUSED`

![image](https://github.com/jowilf/starlette-admin/assets/13135006/cb5cf4dd-01cd-47bd-b6ea-6e65bd7cc7e4)

**Comment by jowilf** [comment]
Thank you for reporting this. You can now access it.

**Comment by hasansezertasan** [comment]
@jowilf, this issue is recurring at the moment.

**Comment by jowilf** [comment]
@hasansezertasan it's live again. Thanks
