### ISSUE TITLE
Bug: custom row actions need a "can_use_action" equivalent

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#524]
**Describe the bug**

A ```delete``` row action can only be visible if  ```can_delete``` returns true.

I need the same power for a new row action I am adding. Unfortunately this does not seem possible, or at a minimum it is not documented at https://jowilf.github.io/starlette-admin/tutorial/actions/

**To Reproduce**

Add a row action and try to make it so that it is only visible when delete is visible, for example. Or some fancier rule, like a given logged user email.

**Environment (please complete the following information):**

- Starlette-Admin version: 0.13.1
- ORM/ODMs: SQLAlchemy, psycopg2-binary==2.9.9
- SQLAlchemy-serializer==1.4.1

**Additional context**

Perhaps the ```@row_action```decorator should take an extra param, which is the name of the method for "can_use_action". It would be like the existing ones for delete/can_delete,  edit/can_edit, view/can_view_details

**Comment by Ilya-Green** [comment]
```
class UserView(MyModelView):
        @action(
        name="archive",
    )
    async def archive(self, request: Request, pks: List[Any]) -> str:
        session: Session = request.state.session
        for user in await self.find_by_pks(request, pks):
            //some logic
        return "{} clients were successfully changed to responsible with id: {}".format(
            len(pks), request.query_params["id"]
        )

    async def is_action_allowed(self, request: Request, name: str) -> bool:
        if name == "arhcive":
            if request.state.user["sys_admin"]: //there can be any condition
                return True
        if name == "delete":
            return self.can_delete(request)
        return True
```

**Comment by sglebs** [comment]
Thanks! Is that a suggestion for the future or does it work today? If it works today, then:

  - how about adding it to documentation?
  - why do some actions (delete, edit, view) get their own methods but these extra actions get a single method which requires a "switch statement" to decide if that extra action can be applied? Shouldn't we have a uniform mechanism?

**Comment by sglebs** [comment]
Answering my own points, here's what works, based on the tips given:

```
    async def is_action_allowed(self, request: Request, name: str) -> bool:
        # first I must handle all the "built-ins"
        if name == "view":
            return self.can_view_details(request)
        if name == "edit":
            return self.can_edit(request)
        if name == "delete":
            return self.can_delete(request)
        # now the new one
        if name == "my_new_action":
            return self.can_perform_myNew_action(request)
        return False
```

**Comment by hasansezertasan** [comment]
Your approach looks like how it should have been done 👍.

I have another recommendation here, the WTForms magic method approach to validate fields is the main inspiration. [A basic example of WTForms Custom Validations](
https://wtforms.readthedocs.io/en/2.3.x/validators/#custom-validators).

Consider you have an action called 'something'. What do you need to access control this action? Override the `is_action_allowed` method  and update it for each action. What about a dynamic approach that enables you to implement less code smell? (Possibly never ending if approach here is a bit smelly to me.) The `can_use_{action_name}` syntax... So we can go like this:

```python
    def can_use_something(...):
        # Logic goes here...
```

The only and major downside I can see is that there won't be any editor support for type annotations and autocompletion on this new magic method. 

I know its a bit too magic but still, I'd like to hear what do you people think about this design? What downsides does it have?
