### ISSUE TITLE
Bug:  relationship object not available in EDIT template but available in DETAIL template

### ISSUE THREAD

**Issue by sglebs** [jowilf/starlette-admin#534]
**Describe the bug**

I overrode both the DETAIL  template and the EDIT template of my object/table (let's call it Foo).  It has a relationship to another object/table, named Client:

```
    client_id = Column(ForeignKey('clients.id', ondelete='SET NULL', onupdate='CASCADE'))
    client = relationship('Client')
```

This Client object has a field/column, vhost, which is a String.

I have this snippet in my temple for both EDIT and DETAIL:

```
data-backend-host="{{ obj["client"]["vhost"] }}"

```

Then I am looking at my entity, the value is populated. When I am editing, I get an empty string.

What I SUSPECT: in EDIT mode the relationships are fetched in a lazy fashion, perhaps? I need to force the loading, perhaps? How?

**To Reproduce**

Well, in any of your objects/entities/tables, override EDIT and DETAIL templates and print a property of a related entity. 

**Environment (please complete the following information):**

Starlette-Admin version: 0.13.1
ORM/ODMs: SQLAlchemy, psycopg2-binary==2.9.9
SQLAlchemy-serializer==1.4.1

**Additional context**

**Comment by sglebs** [comment]
In EDIT mode, obj["client"] is a STRING !!!!!   I tried ```obj["client"].vhost.get()``` (based on https://stackoverflow.com/questions/25675569/how-to-access-properties-of-referenced-objects-in-jinja2-templates-google-app-e) but got  ```jinja2.exceptions.UndefinedError: 'str object' has no attribute 'vhost' ```

Obviously ```obj["client"].get().vhost ``` does not work either.

**Comment by sglebs** [comment]
I could really use some help on this one. Any tips on how to move forward?

**Comment by hasansezertasan** [comment]
> I could really use some help on this one. Any tips on how to move forward?

Can you share a minimal example as a starting point? I'll try to take a look at.

**Comment by jowilf** [comment]
The edit template only uses the value of the primary key https://github.com/jowilf/starlette-admin/blob/7465db977d748baa43c3f39a20a307c3636bd7be/starlette_admin/views.py#L722

 You can use the `raw_obj` https://github.com/jowilf/starlette-admin/blob/7465db977d748baa43c3f39a20a307c3636bd7be/starlette_admin/base.py#L458 ). 

Here's an example: https://github.com/jowilf/starlette-admin-demo/blob/a1bc5d09dd6a11ecb17a6a834031c1ad4cc6561c/templates/admin/sqla/post_detail.html#L81

**Comment by sglebs** [comment]
Worked like a charm. Than you so much!
