### ISSUE TITLE
Bug: Edit and View buttons in rows have 'undefined' hrefs in version 0.13 (up) but not in version 0.11

### ISSUE THREAD

**Issue by samearcher** [jowilf/starlette-admin#545]
**Describe the bug**
I'm managing a materials database using Starlette-Admin. This has been working in version 0.11, but I've upgraded to 0.13 to make use of column_property.
This works ok except the edit and view buttons on each row have undefined hrefs so the links produce error 404.
This is the HTML served up under 0.13:

<img width="339" alt="image" src="https://github.com/jowilf/starlette-admin/assets/73623168/9c3b45b5-907c-43cc-9a62-15317d103b67">

Under 0.11:

<img width="315" alt="image" src="https://github.com/jowilf/starlette-admin/assets/73623168/05ae4069-03c8-448b-a30b-44c352d13c13">

The model:
```
class A1_A3_Data_Base(BaseModel):
    
    material_class: Optional[str] = Field(default='STRUCTURE')
    mat_class_id: Optional[int] = Field(default=None, foreign_key="material_class.id")
    sheet_title: Optional[str] = Field(default='')
    table_heading: Optional[str] = Field(default='')
    table_subheading: Optional[str] = Field(default='')
    product_code: Optional[str] = Field(default='')
    material: Optional[str] = Field(default='')
    qty_basis: Optional[str]
    a1_a3_CO2: Optional[float]
    a1_a3_energy_total: Optional[float] 
    a1_a3_energy_non_renewable: Optional[float]
    a1_a3_energy_renewable: Optional[float] = Field(default=0)
    notes: Optional[str] = Field(default='')
    data_quality: Optional[Data_quality] = Field(default=Data_quality.A)
    density: Optional[float]
    area_density: Optional[float]
    linear_density: Optional[float]
    mass_per_unit: Optional[float]
    length: Optional[float]        


class A1_A3_Data_Create(A1_A3_Data_Base):
    pass

class A1_A3_Data(A1_A3_Data_Base, SQLModel, ActiveRecordMixin, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    mat_class: Material_Class = Relationship(back_populates="a1_a3_data")

    async def __admin_repr__(self, request: Request):
        return f"{self.table_heading, self.table_subheading}"
```
**To Reproduce**
Explain how to reproduce the bug.

**Environment (please complete the following information):**
 - Starlette-Admin version: [e.g. 0.11 and 0.13]
 - ORM/ODMs: [SQLAlchemy]
 - Database model: [SQLModel]

**Additional context**

**Comment by jowilf** [comment]
Try deleting your browser cache.

**Comment by samearcher** [comment]
Thanks @jowilf , yes that worked. Thanks!
