### ISSUE TITLE
Help: change the actual column name in Model

### ISSUE THREAD

**Issue by viaoi** [jowilf/starlette-admin#562]
**Describe the bug**
i want change the actual columns name in admin panel 

brand in panel  want display with ”品牌“

class CPU(Base):
    __tablename__ = "cpu"
    id: Mapped[int] = mapped_column(primary_key=True)
    brand: Mapped[str] = mapped_column(info="品牌")
    model: Mapped[str] = mapped_column(info="型号")
    architecture: Mapped[str] = mapped_column(info="架构")

**Comment by hasansezertasan** [comment]
You could use fields to customize column name.

**Comment by cx4** [comment]
> You can use fields to customize column name.

Do I need to create a class inheriting from StringField for each field to implement it? Is there a simpler way to achieve this? If there are many fields to be processed, is it only necessary to modify the name displayed in the table header.

**Comment by jowilf** [comment]
You can provide your own field for each attribute. Here is an example 
 https://github.com/jowilf/starlette-admin/blob/5b183e0138300d27c80b933696b4ccc438060886/examples/sqla/views.py#L60

If you decide to customize the Brand label in the model CPU for example, you can do something like this:

```py
class CPUView(ModelView):
      fields = [
          "id",
           StringField("band", label="Custom Brand label"),
           "model",
           ...
      ]

**Comment by cx4** [comment]
> You can provide your own field for each attribute. Here is an example
> 
> https://github.com/jowilf/starlette-admin/blob/5b183e0138300d27c80b933696b4ccc438060886/examples/sqla/views.py#L60
> 
> If you want to customize the Brand label in the model CPU for example, you can do something like this:
> 
> ```python
> class CPUView(ModelView):
>       fields = [
>           "id",
>            StringField("band", label="Custom Brand label"),
>            "model",
>            ...
>       ]
> ```

Thank you for your example. You are really amazing and so Kindly
