### ISSUE TITLE
Bug: no https in stylesheet and actions

### ISSUE THREAD

**Issue by dandaniel5** [jowilf/starlette-admin#571]
i do this 2 from deployment [docs](https://jowilf.github.io/starlette-admin/deployment/)
1. Ensure that your proxy server is properly configured to handle HTTPS traffic.
2. When starting your application with Uvicorn, include the --forwarded-allow-ips and --proxy-headers options. These options enable Uvicorn to correctly handle forwarded headers from the proxy server.
HOWEVER i get this annoying message everywhere 
<img width="608" alt="image" src="https://github.com/user-attachments/assets/181c4d96-2c7f-4efd-96ad-da25d4f12428">

yes CRUD kinda work, but i cannot rely use it in prod. your siluion just mask the problem but not solve it
<img width="172" alt="image" src="https://github.com/user-attachments/assets/00c1f0dc-b62e-4a01-8768-3aa64d14251b">
may be you can add prod and dev mode 4 it works with and without https

**Comment by jowilf** [comment]
Can you provide more context? which proxy server are you using? 
For example, the [demo website](https: //jowilf.github.io/starlette-admin/) is https and everything works fine.

**Comment by dandaniel5** [comment]
I’m using Nginx, but how can it change internal files? I think the <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> tag may update the request to HTTPS, but the links in the code are still using HTTP, which causes a warning because the links are still set to HTTP.

**Comment by jowilf** [comment]
Here is the complete guide for deploying behind nginx: https://www.uvicorn.org/deployment/#running-behind-nginx

**Comment by dandaniel5** [comment]
how it will chang http in template ? uvicarn and other stuff working great im ny setup. exept http in your templstes. ok if you cannot understand mu problem i will go do egg insterd.

**Comment by dandaniel5** [comment]
Ok, the egg was kind of an extreme idea, so I decided to change some files — create.html and edit.html. I made the change directly in lines 21:

<form action="{{ request.url | replace('http://', 'https://') | safe }}" method="POST" enctype="multipart/form-data">

**Comment by jowilf** [comment]
>  how it will chang http in template 

The form is accessing s the current request URL through `request.url` to access. This is not a starlette-admin issue but your proxy server fails to send the appropriate headers to your starlette/fastapi application.

Please follow this guide  https://www.uvicorn.org/deployment/#running-behind-nginx . Similar issue: https://github.com/jowilf/starlette-admin/issues/280
