### ISSUE TITLE
Deprecation Warning for **env_options in Jinja2Templates with Starlette >=0.28.0

### ISSUE THREAD

**Issue by ptrstn** [jowilf/starlette-admin#574]
I'm encountering a deprecation warning related to `Jinja2Templates` when running `pytest` tests with `starlette>=0.28.0` :

```
.venv/lib/python3.11/site-packages/starlette/templating.py:106: DeprecationWarning: Extra environment options are deprecated. Use a preconfigured jinja2.Environment instead.
    warnings.warn(
```

This warning does not appear when installing `starlette==0.27.0`

According to the [Starlette 0.28.0 release notes](https://www.starlette.io/release-notes/#0280), the `**env_options` parameter in `Jinja2Templates` has been deprecated in favor of the new `env` parameter. The relevant pull request [#2159](https://github.com/encode/starlette/pull/2159) explains this change.

It seems likely that Starlette Admin (or other dependencies) are still using the deprecated `**env_options`, causing the warning when running tests with Starlette 0.28.0.

### Steps to Reproduce:

1. **Project Structure:**
    
    ```
    .
    ├── app.py
    ├── requirements-deprecation-warning.txt
    ├── requirements-no-warnings.txt
    └── test_app.py
    ```
    
2. **Source Code:**
    
    **`app.py`:**
    ```python
    from fastapi import FastAPI
    from starlette_admin.contrib.sqlmodel import Admin
    from sqlmodel import SQLModel, create_engine
    
    DATABASE_URL = "sqlite:///./test.db"
    engine = create_engine(DATABASE_URL, echo=True)
    SQLModel.metadata.create_all(engine)
    
    app = FastAPI()
    admin = Admin(engine, title="Simple Admin")
    admin.mount_to(app)
    ```
    
    **`test_app.py`:**
    ```python
    import pytest
    from fastapi.testclient import TestClient
    from app import app
    
    @pytest.fixture(scope="module")
    def client():
        with TestClient(app) as client:
            yield client
    
    def test_admin_page(client):
        response = client.get("/admin")
        assert response.status_code == 200
        assert "Simple Admin" in response.text
    ```

3. **Requirements Files:**

    **`requirements-deprecation-warning.txt`:**
    ```
    fastapi
    sqlmodel
    uvicorn
    starlette-admin
    jinja2
    sqlalchemy
    starlette==0.28.0
    pytest
    httpx==0.24.1
    ```
    
    **`requirements-no-warnings.txt`:**
    ```
    fastapi
    sqlmodel
    uvicorn
    starlette-admin
    jinja2
    sqlalchemy
    starlette==0.27.0
    pytest
    httpx==0.24.1
    ```

4. **Reproduce the Warning:**
   
    ```bash
    pip install -r requirements-deprecation-warning.txt
    pytest
    ```
    **Result:** Deprecation Warning
    
    
     ```bash
     pip install -r requirements-no-warnings.txt
     pytest
     ```
    **Result:** All tests pass without warnings.

**Comment by ptrstn** [comment]
I think the issue lies in these lines:

https://github.com/jowilf/starlette-admin/blob/5b183e0138300d27c80b933696b4ccc438060886/starlette_admin/base.py#L192-L199

The [signature of Jinja2Templates](https://github.com/encode/starlette/blob/c78c9aac17a4d68e0647252310044502f1b7da71/starlette/templating.py#L66-L74) looks like this:

```python
class Jinja2Templates:
    @typing.overload
    def __init__(
        self,
        directory: str | PathLike[str] | typing.Sequence[str | PathLike[str]],
        *,
        context_processors: list[typing.Callable[[Request], dict[str, typing.Any]]]
        | None = None,
        **env_options: typing.Any,
    ) -> None: ...
```

So `extensions=["jinja2.ext.i18n"]` is passed indirectly through the `**env_options` argument of `Jinja2Templates` in Starlette.

**Comment by ptrstn** [comment]
Something like this should do the job:

```python
from jinja2 import ChoiceLoader, Environment, FileSystemLoader, PackageLoader

def _setup_templates(self) -> None:
    env = Environment(
        loader=ChoiceLoader(
            [
                FileSystemLoader(self.templates_dir),
                PackageLoader("starlette_admin", "templates"),
            ]
        ), 
        extensions=["jinja2.ext.i18n"]
    )
    templates = Jinja2Templates(env=env)
 ```
 
 But  raises another Warning: 
 
 ```python
 DeprecationWarning: The `name` is not the first parameter anymore. The first parameter should be the `Request` instance.
  Replace `TemplateResponse(name, {"request": request})` by `TemplateResponse(request, name)`.
    warnings.warn(
```

After further examination I saw that the parameters of [`TemplateResponse`](https://github.com/encode/starlette/blob/c78c9aac17a4d68e0647252310044502f1b7da71/starlette/templating.py#L166-L178) are [swapped](https://fastapi.tiangolo.com/reference/templating/#fastapi.templating.Jinja2Templates.TemplateResponse) in `_render_error`:

https://github.com/jowilf/starlette-admin/blob/5b183e0138300d27c80b933696b4ccc438060886/starlette_admin/base.py#L489-L499

and should rather look like [this](https://fastapi.tiangolo.com/advanced/templates/#using-jinja2templates):

```python
 async def _render_error( 
     self, 
     request: Request, 
     exc: Exception = HTTPException(status_code=HTTP_500_INTERNAL_SERVER_ERROR), 
 ) -> Response: 
     assert isinstance(exc, HTTPException) 
     return self.templates.TemplateResponse( 
         request=request,
         name="error.html", 
         context={"exc": exc}, 
         status_code=exc.status_code, 
     ) 
```

Also in all the other instantiations of TemplateResponse in base.py:
- `_render_list`
- `_render_detail`
- `_render_create` (2x)
- `_render_edit` (2x)

In auth.py:
- `render_login` (3x)

And in views.py:
- `render`

**Comment by jowilf** [comment]
Hi @ptrstn, thank you for reporting this. Please feel free to submit a PR to fix it.
