### ISSUE TITLE
Bug: dont show relationship field

### ISSUE THREAD

**Issue by ps96068** [jowilf/starlette-admin#584]
Hi there,

I'm trying to implement starlette-admin in my FastAPI project.

some description about what i do:

one my model:

```
class Company(Base):
    __tablename__ = "companies"

    id: Mapped[int] = mapped_column(primary_key=True, unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    .........
    users: Mapped[list["User"]] = relationship("User", back_populates="company")
```

starlette-admin ModelView for this model:

```
class CompanyView(ModelView):
    fields = [
        'id', 'name', 'users'
    ]

company_view = CompanyView(model=Company, icon = "fa-solid fa-user",
                           name="Company", label="Company", identity="companies")
```

in my project main file:

```
app = FastAPI()
app.mount("/static", StaticFiles(directory="static", html=True), name="static")

admin_panel = Admin(engine=engine, title="Welcome Admin",
                    base_url="/admin", route_name="admin",
                    auth_provider=AdminAuthProvider(),
                    middlewares=[Middleware(SessionMiddleware, secret_key=SECRET_KEY)])

admin_panel.add_view(company_view)
admin_panel.mount_to(app)

```

I added a company to the database
I added a user to the database
when I try to access the Company model in starlette-admin, only the fields are displayed, but the 404 error appears in the console:

INFO:     127.0.0.1:64096 - "GET /admin/api/companies?skip=0&limit=10&order_by=id%20asc HTTP/1.1" 404 Not Found

can somebody help me?

**Comment by jowilf** [comment]
you need to add a view for the user as well. 

```py
admin.add_view(ModelView(User))
```
You can use https://jowilf.github.io/starlette-admin/api/views/#starlette_admin.views.BaseView.is_accessible if you don't want it to appear on the dashboard.
