### ISSUE TITLE
Inline models

### ISSUE THREAD

**Issue by logicli0n** [jowilf/starlette-admin#588]
**Is your feature request related to a problem? Please describe.**
Add inline models 

**Describe alternatives you've considered**
Django, Flask-Admin

**Additional context**
![django-inline-in-fieldset-with-css](https://github.com/user-attachments/assets/4fceaf9b-573a-47b1-8f6d-f2e4bfc6d64a)

**Comment by jowilf** [comment]
similar to #440 
A workaround: #240

**Comment by logicli0n** [comment]
class Shipment(Base, Mixin):
    __tablename__ = "shipment"
    date_to_ship: Mapped[datetime.datetime]
    vehicles: Mapped[list["Vehicle"]] = relationship("Vehicle", back_populates="shipment")


class Vehicle(Base, Mixin):
    __tablename__ = "vehicle"
    make: Mapped[str]
    model: Mapped[str]
    year: Mapped[int]
    shipment_id: Mapped[int] = mapped_column(ForeignKey("shipment.id"))
    shipment: Mapped["Shipment"] = relationship("Shipment", back_populates="vehicles")
    file:Mapped[dict] = mapped_column(FileField)           <-----------------------------------


field=CollectionField(
                "vehicles",
                fields=[
                    IntegerField(
                        name="id",
                        label="ID",
                        help_text="ID of the record.",
                        read_only=True,
                    ),
                   ................................................
                   FileField("file")
                ],
)

@jowilf  I have FileField in Vehicle.I added this FileField in CollectionField, but get error ----->  Unable to determine the file's size.


File "/usr/local/lib/python3.12/site-packages/sqlalchemy_file/file.py", line 66, in init
size = get_content_size_from_fileobj(self.original_content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/sqlalchemy_file/helpers.py", line 63, in get_content_size_from_fileobj
raise RuntimeError("Unable to determine the file's size.") # pragma: no cover
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to determine the file's size.
