### ISSUE TITLE
Bug: NotSupportedColumn UUID

### ISSUE THREAD

**Issue by aybruhm** [jowilf/starlette-admin#64]
**Describe the bug**
Startletter-admin does not support uuid column

**To Reproduce**
- import `from sqlalchemy.dialects.postgresql import UUID`
- add `uuid = Column(UUID(as_uuid=True), default=uuid.uuid4, unique=True)` to table

**Environment:**
 - Starlette-Admin version: 0.5.0
 - ORM/ODMs: SQLAlchemy
 - Framework: FastAPI
 - Database: PostgreSQL

**Additional context**
When I take out the UUID column from the database table, the admin interface works. And when I add it back, it gives me this error:
    ```raise NotSupportedColumn(  # pragma: no cover
starlette_admin.contrib.sqla.exceptions.NotSupportedColumn: Column UUID is not supported```

However, when I accessed this file `starlette_admin/contrib/sqla/helpers.py`, line `149`, in the `convert_to_field` function, I see that it supports `"dialects.postgresql.base.UUID": StringField`

**Comment by jowilf** [comment]
Thank for reporting this
