### ISSUE TITLE
Bug: Not found routes

### ISSUE THREAD

**Issue by bakrianoo** [jowilf/starlette-admin#67]
**Describe the bug**
Hi
I am facing a weird issue that some routes are discovered while the others return 404

For example, the following route can be retrieved 

![image](https://user-images.githubusercontent.com/14326057/209671007-65512652-73c2-4f79-bb82-95392f44bbb1.png)

while on the same page, there's an XHR request for another route which returns 404, as illustrated in the following screenshot

![image](https://user-images.githubusercontent.com/14326057/209671145-25687a22-590e-44c4-81b4-a932ca362aef.png)

**To Reproduce**
Here's the sample code I am using

```python

class Bots(Base):
    __tablename__ = "bots"

    bot_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    bot_name = Column(String, unique=True, index=False)
    bot_config = Column(MutableDict.as_mutable(JSONB), default="{}")
    
    bot_created_at = Column(DateTime(timezone=True), server_default=func.now())
    bot_updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    intents = Column(String, unique=False, index=False)

app = FastAPI() # I tried Starlette() too

admin = Admin(engine, title="Example: SQLAlchemy", base_url="/root")

admin.add_view(ModelView(Bots))
admin.mount_to(app)

```

**Environment (please complete the following information):**
 - Starlette-Admin version: 0.5.1
 - ORM/ODMs: SQLAlchemy

**Comment by jowilf** [comment]
Hello @bakrianoo ,

Please, can you try on your local machine first ?

**Comment by jowilf** [comment]
I'm not sure this bug is related to starlette-admin, Feel free to reopen it if you 're not satisfied
