### ISSUE TITLE
Enhancement: logging and/or more explicit form validation exceptions

### ISSUE THREAD

**Issue by sshghoult** [jowilf/starlette-admin#69]
**Is your feature request related to a problem? Please describe.**
I've spent this night in pitiful attempts to understand why the **{identity}/edit/{pk}** view's form submission **didn't trigger the update** command in my mongodb - create, list and detail worked fine, in the example the aforementioned view worked fine, but it silently refused to act properly in my case. 
The reason for it is the fact that the on-write **validation** on my UUID field for that model **fails** but the **error message** about it **can't be displayed** on the frontend since that field is not a part of the ModelView. I found it out after overwriting the _edit_ async method for my ModelView and adding logging there.

The case I encountered goes like this:
1. Update the included fields 
2. Click "Submit"
3. Be redirected to the very same page with no explicit warnings on the result
4. Check the logs - 200 on POST
5. Check the DB and item list - see the unchanged item

_6. Curse elaborately and spend the night researching the guts of the library to understand what exactly is going on._

**Describe the solution you'd like**
- First of all, it's a dreadful idea to return _200 OK_ for every type of result, especially an internal _ValidationError_. There really should be certain differentiation, that's what http result codes are for.
- Secondly, it would be good to see the exception details in the reason of the response in debug mode, so no similar confusion will arise when the error is related to a non-visible field.
- Thirdly, some form of architectural decision must be made regarding the model errors that currently can't be shown through the ModelView (as goes the one described).
- Finally, there clearly should be some controllable logging wired through the library to facilitate the investigations (and help the library improve and grow long-term).

**Comment by jowilf** [comment]
Hello @sshghoult,

This is typical night of a good software engineer :)

First, If you exclude some fields from your ModelView, you should make sure that, it is possible to CRUD your model without these fields.

Also I believe, if your just configured logging with your ORM ( example `echo=True` for sqlachemy), it is sufficient (with requests logging handled by starlette) to understand what going on. A possible solution could be to display others errors on top

For http code, i think you're right, it should be `422 Unprocessable Entity`

**Comment by jowilf** [comment]
#74 is now release in 0.6.0

**Comment by ricardogsilva** [comment]
@jowilf can we reopen this?

It would be nice to have some feedback for when there are validation errors in the logs, as it can otherwise be hard to debug trivial issues.

In my current case I was forgetting to add one field to my model and requests just failed with `HTTP 422` and nothing else:

```
INFO:     127.0.0.1:39976 - "POST /admin/todo/create HTTP/1.1" 422 Unprocessable Content
```

After I added a simple logging strategy to my model I could instantly spot the problem:

```python
pydantic_core._pydantic_core.ValidationError: 1 validation error for Todo
stuff
  Field required [type=missing, input_value={'title': 'first', 'done'...546875, 3.074695072]]]}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing
```

In order to get this I only had to redefine the `handle_exception()` method:

```python
import logging
logger = logging.getLogger(__name__)


class TodoView(ModelView):
    fields = (
        # omitted for brevity
    )

    def handle_exception(self, exc: Exception) -> None:
        logger.exception("An exception occurred")
        return super().handle_exception(exc)
```

Granted, this is not very hard to add on my part, but I think it would be nicer if starlette-admin had error logging by default.

If you agree that this is a relevant thing, I can prepare a PR.
