### ISSUE TITLE
Enhancement: UUID field

### ISSUE THREAD

**Issue by sshghoult** [jowilf/starlette-admin#70]
I have a strong feeling that there should be a standard implementation to display a UUID Field as a part of the ModelView. 

UUID is a de facto standard for unique indexation in distributed systems and quite commonly used as a primary key for entities. Even early on I already have a use case where i would like to display and use it as a part of my admin panel.

**Comment by jowilf** [comment]
I'm not sure this is an issue, Feel free to reopen it if you 're not satisfied

**Comment by sshghoult** [comment]
Sorry for the silence - holidays.

The specific problem I encountered is about integration of _starlette_admin.contrib.mongoengine.ModelView_ with _mongoengine_ model. 

Let's start from the beginning. I use mongoengine models as secondary ODM models in order to use the starlette_admin on top of my mongodb. My primary CRUD ODM is Beanie, which handles the data manipulation requests coming from the REST API. ModelView's and mongoengine models are used to edit the existing objects through admin panel.

When i declare _mongoengine.fields.UUIDField_ as a field of _mongoengine.Document_ and later add a _starlette_admin.StringField_ field on top of it in a related _ModelView_, on retrieval the StringField seems to contain the string representation of the <class 'bytes'> of the stored uuid. E.g. the value displayed by the admin panel front-end for one of the objects is a string "b'YJ\\\n\x91 \x11\xed\xa5\x9c\x02B\xac\x12\x00\x03'" (without the double quotation marks). 

On edit, the form and form-parsing treat it like a simple string and try to write it into the underlying _mongoengine.fields.UUIDField_, which raises an appropriate ValidationError (e.g. "ERROR:root:ValidationError (Review:63bdc20c3b2dfba668718b63) (Could not convert to UUID: badly formed hexadecimal UUID string: ['public_id'])", where "Review" is the name of the model and "public_id" is the name of the field).

While I was writing this issue, I found the probable cause: 
- the type of uuid-storing field inside the mongodb, when the object is saved through **Beanie** is
"public_id: new **UUID("594a5c0a-9120-11ed-a59c-0242ac120003")**", (so all my objects are created with this type of field holding the data)
- the type of that field when the object is saved through **mongoengine** is 
"public_id: **Binary(Buffer.from("3b241101e2bb42558caf4136c566a961", "hex")**, 3)" (binary=True)

When the creation of object is carried through the mongoengine, everything works fine.


Therefore, apparently, it's a weird edge case, where StringField-like behaviour is not enough and specific conversions from and to binary form must be made in order to integrate with this type of mongodb storage field.

Reproducable example:

```
import mongoengine as me

class Review(me.Document):
    _id = me.ObjectIdField
    author_name = me.StringField()
    public_id = me.UUIDField()
    meta = {"strict": False}

from starlette_admin.contrib.mongoengine import ModelView
from starlette_admin import StringField


class ReviewView(ModelView):
    fields = [
        StringField("author_name", label="Author's name"),
        StringField("public_id", label="Product UUID")
    ]

    identity = ("review",)
    label = ("Review",)
    document = Review
```

However, I'm now not sure whether this is actually a library problem, or it should be resolved locally. In the end, i think everyone will benefit from the intercompatibility option, so i'll reopen the issue.

Being the topic starter, I feel like I an the one to solve this aberrantly specific problem, but i have a suspicion that instead of solving it here I'll end up inventing a custom mongonengine type for uuids that will behave like it's Beanies' counterpart. 
So it's your call, **jowilf**, whether something should be done about it or not.

**Comment by jowilf** [comment]
Hello @sshghoult,
I don't think it's a good idea to manage the same data by two different ODM.

Starlette-admin will support beanie in future but right now the only choice you have is to implement the CRUDs methods for your ModelView ([doc](https://jowilf.github.io/starlette-admin/advanced/base-model-view/), [example](https://github.com/jowilf/starlette-admin/tree/main/examples/custom-backend))

Also you can try ODMantic which is based on pydantic like Beanie

**Comment by sshghoult** [comment]
Yep, I agree, the notion of using two different ODMs put me off on sight, but at that moment the only alternative I could see was to implement the beanie support from scratch, so I took the risk.

Thank you for the hint about CRUD methods on ModelView, will try that!
