### ISSUE TITLE
Bug: EnumField options displayed incorrectly in list/detail templates

### ISSUE THREAD

**Issue by sshghoult** [jowilf/starlette-admin#95]
When I use EnumField.from_choices(<name>, [(<value>, <label>), ]) to define a field on my ViewModel, enum members' labels are displayed appropriately on the edit template, but on the list and detail templates the values are displayed instead of the labels.

Cause: EnumField.display_template is the BaseField.display_template, which is "displays/text.html". This template blindly uses the value instead of the label.

Reason to fix: this bug noticebly harms human readability, since Enums are commonly used as process statuses. 
It also damages the internationalization attepmpts (however, that's a whole other issue).

How to fix: add a display template

**Comment by jowilf** [comment]
I'm not sure you are using it the right way, please refer to this [example](https://github.com/jowilf/starlette-admin/blob/5c8ea521e064cc1f5048c67dcc40babc278d4139/examples/sqla/views.py#L25) for how to use it or provide minimal code to reproduce your bug


> Cause: EnumField.display_template is the BaseField.display_template, which is "displays/text.html". This template blindly uses the value instead of the label.

As you can see [here](https://github.com/jowilf/starlette-admin/blob/5c8ea521e064cc1f5048c67dcc40babc278d4139/starlette_admin/fields.py#L380), the template use the label
