### ISSUE TITLE
Bug: error page is not rendered, if exception occurs in delete methods

### ISSUE THREAD

**Issue by dolamroth** [jowilf/starlette-admin#99]
**Describe the bug**
If I try to delete object via admin panel, template "error.html" is not displayed. Instead, it arrives as response to AJAX query (visible in browser console).

**To Reproduce**
I am using starlette_admin with sqlalchemy contrib module. Simply override method `delete` in `starlette_admin.contrib.sqla.view.ModelView` to raise `starlette.exceptions.HTTPException(500)`.

**Environment (please complete the following information):**
- browser: Mozilla Firefox 110.0
- starlette==0.25.0
- starlette-admin==0.5.2
- SQLAlchemy==1.4.46

**Additional context**

**Comment by jowilf** [comment]
ModelView.delete method is used as action, You need to raise `ActionFailed(msg)` to display a meaningfully error. More info https://jowilf.github.io/starlette-admin/tutorial/batch-actions/

-> To be added in the documentation

**Comment by dolamroth** [comment]
Overriding action `delete` in the following way indeed helps

```
    async def delete_action(self, request: Request, pks: List[Any]) -> str:
        try:
            affected_rows = await self.delete(request, pks)
        except SQLAlchemyError as exc:
            raise ActionFailed(str(exc))
        return "{} items were successfully deleted".format(affected_rows)
```

Maybe it would be better to override default `starlette_admin.contrib.sqla.view.ModelView.delete_action` to wrap any `sqlalchemy.exc.SQLAlchemyError` with re-raising ActionFailed, what do you think? I could provide a PR.

**Comment by dolamroth** [comment]
There still seems to be a bug with "delete" on item page `/admin/{entity}/detail/{id}`. 

After trying to delete an instance, I get empty modal window and in browser console there is JSON response 
```
{"msg": "(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>..."}
```


From what I see in JS handler, text is not set in modal window.
```
function() {
  $("#modal-delete").modal('hide');
  $("#modal-loading").modal('show');
  fetch("......", {
    method: "POST",
  }).then(async response => {
    if (response.ok) {
      await new Promise(r => setTimeout(r, 500));
      $("#modal-loading").modal('hide')
      window.location.replace(".........")
    } else
      return Promise.reject();

  }).catch(async (error) => {
    await new Promise(r => setTimeout(r, 500));
    $("#modal-loading").modal('hide')
    $("#modal-error").modal('show');
  });
}
```
